### ISSUE TITLE
Verify that a File Manifest includes shelve or preserve set to "yes"

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/pre-assembly#1117]
If a file manifest is submitted where both "shelve" and "preserve" are set to "no" for a specific file, then the file is ultimately discarded. If a user forgets to set one of those values at all (i.e. it's left blank on the CSV) this will result in the field being set to no on deposit.

There is no use case for submitting a content file with both shelve and preserve set to no, as that would indicate that there was no need to deposit the file at all. A file_manifest with both fields set to "no" or left blank accidentally is almost certainly a mistake and the system should stop the job and report back a message to the user.

As part of the discovery report we should validate that at least one of the two fields is set to yes, which will catch both the case where both fields are set to "no" and the case where one field is set to "no" and another is left blank. 

Context: I found this issue when I made a mistake in my own accessioning job on stage and discovered that one file had been discarded.

**Comment by peetucket** [comment]
It doesn't look like we currently do **not** verify if the file_manifest has all the correct columns (like we do for the other manifest file which requires "druid" and "object").  Should we do that at the same time as looking for the preserve/shelve stuff (would be a simple addition to the same part of the code being added to)?

e.g. verify we have "object,filename,label,sequence,publish,shelve,preserve,resource_type,role"
