### ISSUE TITLE
When using the media content type, always check for a file manifest

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/pre-assembly#1158]
**Describe the bug**
Accessioning media requires the use of a file manifest. If a user forgets to check the "I have a file manifest" box, the system fails with the following error reported to the Preassembly job log:

```
:pre_assem_finished: false
:status: error
:message: undefined method `capitalize' for nil:NilClass
:pid: bg977ts4975
:container: "/smpl2/digreq-2155/b6f/content/bg977ts4975"
:timestamp: '2023-04-20 21:07:25'
```

**Expected behavior**
Since a file manifest is the only way to create streaming media items correctly, the file manifest box should either automatically be checked when selecting media or the system should always look for a file manifest regardless of what the interface shows.

**Additional context**
It used to be that the file manifest was required when accessioning media and there was no box to check. When we made the file manifest available for other content types, we had to add something to the UI so users could indicate whether to apply the extra manifest or not. One possibility would be to remove the box and always look for a file manifest. In that case, some content types could proceed without a manifest while others would require it.

**Comment by peetucket** [comment]
The simplest way to achieve this is with an additional validation on the form itself, all server side.  So if you submit the form having selected "Media" but not checked "I have a file manifest", you will get an error message.  There is already a separate check for the file's existence if the checkbox is checked.  We don't currently have any Javascript UI libraries or smarts (like we do in H2), and I'd propose not adding it here (to, for example, auto-check the box in the UI if the user selects "Media").
