### ISSUE TITLE
Re-name "content metadata creation" to "processing configuration"

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/pre-assembly#1180]
The Preassembly form contains a dropdown menu labeled "content metadata creation":

<img width="838" alt="Preassembly content metadata creation menu" src="https://github.com/sul-dlss/pre-assembly/assets/8975583/9d3e3510-3715-4974-bcf2-088dba396798">

The label refers to "content metadata", which was the name given to structural metadata in the old Fedora model. The function of the menu is to provide an instruction for how Preassembly should create structural metadata. In other words, it is literally about "content metadata creation".

**Background: what the content metadata creation setting does**

Currently, there are two settings on this menu:

- "default" = every file will be made into its own "resource"
- "filename" = files will be grouped into "resources" based on filename patterns

The main use cases for the "filename" pattern is when the content being accessioned contains multiple files per unit of content: For example, an image or page could contain the following file types:

- TIFF image of page
- JP2 image of page
- PDF of page
- XML representation of OCR of page
- TXT representation of OCR of page

As long as each of those files shares the same filename - except for the extension - they will be grouped together. The image and book viewers expect this kind of grouping.

**Request Re-name that menu to something that makes more sense to users**

Since there's no such thing as "content metadata" anymore, we should change the name. "Structural metadata creation" sounds too literal. Since the menu is about how files should be processed, we could go with a more generic name like: "Processing configuration".

Then we could rename the options on the menu:

- "Default" --> leave this alone
- "Filename" --> "Group by filename"

The result will be:

- Menu title: "Processing configuration"
- Menu options:
 - "Default"
 - "Group by filename"

I want to add another option beyond those two but I will file a new ticket for that.

**Comment by ndushay** [comment]
It may make sense to rename some classes and variables in the app code as well.
