### ISSUE TITLE
EPIC: Track Preassembly job progress through accessioning

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/pre-assembly#1181]
When a Preassembly job is run, Preassembly only reports progress up to when the Preassembly job completes. No progress is tracked through to the end of accessioning. Now that we have the ability for SDR to report back when accessioning is completed (as it does for H2), we should track the status of Preassembly jobs until accessioning is done. The Preassembly UI and email notification logic would be updated to accommodate the new status.

**Proposal**

1. Change the current "Completed" status to "Preassembly completed"
2. Add a status for "Accessioning completed"
3. Do not send an email for "Preassembly completed" - just show this in the UI
4. Send an email for "Accessioning completed" when the final item in the batch job has been accessioned
5. If any item in the batch job hits an error that prevents accessioning from being completed, register that as "Accessioning completed (with errors)" - do not wait until the errors are resolved to report the end of the job, otherwise the email notice could be held for days
6. The log file should indicate what druids hit errors in accessioning

**Motivation**

Tracking accessioning progress is a challenge for users. Even when Preassembly reports success, some items may hit errors during accessioning. Users need to go to Argo and understand the workflow grid to be able to track these down, and often they don't know that there is anything to check until the start to do QA on their content. Including information about accessioning status will let users know right away if some of their content got "stuck". It will also help me as a manager know who to contact if I can identify which error is associated with which Preassembly job.

Tracking accessioning status will also prevent users from attempting to create a new version of an item via Preassembly when it's still in accessioning. Multiple users have run into this issue before because they thought that when Preassembly is completed, accessioning is completed.

**Comment by edsu** [comment]
All the work for this Epic is now complete!
