### ISSUE TITLE
Separate discovery report errors by type into "warnings" and "errors" and treat them separately

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/pre-assembly#1185]
Preassembly discovery reports currently only report successes or errors. The category of error includes two types of problem:

- issues that will cause accessioning to stall or fail
- issues that are usually signs of problems with how content has been staged but which are not always a problem

In the first category are serious problems such as non-existent druids, files that can't be read because of filesystem permissions, files listed in a file manifest that are not staged for accessioning, and so on.

In the second category are problems such as a file that has no extension or an empty folder indicating a druid will have no content.

The second category of error isn't an error in the sense of blocking accessioning. It's really a warning. A user's content might have no extensions in its original state (such as a README file), or a user might be intending to remove all content in an item from public view (hence having an empty folder). 

**Request**
Categorize the existing set of errors as either warnings or errors and treat them differently in the UI.

- Error: do not allow accessioning to run until a discovery report is run that shows no errors
- Warning: allow accessioning to run with warnings. The warning will give people a chance to check their work but should not prevent someone from accessioning if the content is how they intended it to be.

Currently, Preassembly does not prevent users from accessioning even if a discovery report shows errors. Making this change will enable us to require users to run discovery reports prior to running preassembly jobs. We can't enforce a requirement like that right now because there are use cases where users need to ignore those "errors" - these are the situations that should be called warnings.

Ticket #1186 has a preliminary list of "errors" that should be "warnings".

**Comment by andrewjbtw** [comment]
After discussion with @astridu, I think we may not do this at all. We may just keep only one category of "error", which will be simpler for users and for maintenance.

In this approach, we would drop the "warnings" from the error list and not consider them at all. Some analysis is needed to see which errors actually have come up in discovery reports in the last few years. It's possible that the "warnings" are not serving any purpose because they're never being triggered.

**Comment by mjgiarlo** [comment]
Andrew says we should close this. Not gonna do it. Wouldn't be prudent.
