### ISSUE TITLE
Add option to "process configuration" menu: "Group by filename (with OCR)"

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/pre-assembly#1187]
The Preassembly "processing configuration" menu enables user to tell the Preassembly app to follow a specific processing logic when accessioning files.

<img width="838" alt="Preassembly content metadata creation menu" src="https://github.com/sul-dlss/pre-assembly/assets/8975583/9d3e3510-3715-4974-bcf2-088dba396798">

The current options do the following:

- default: treat each individual file as a separate resource/fileset when creating structural metadata
- filename: using filename patterns, group each set of files that differ only in extension into the same resources/filesets

The "filename" option is designed to handle book and image objects where there may be more than one type of file corresponding to a given image or page.

For example, an image or page could contain the following file types:

-    TIFF image of page
-    JP2 image of page
-    PDF of page
-    XML representation of OCR of page
-    TXT representation of OCR of page

Those files would all need to be grouped into the same "page" resource.

**Request**

This ticket is to add another option to the menu: "Group by filename (with OCR)"

What this option will do is similar to "filename" except it will apply settings that specifically enable the use of OCR files to support text search in the Access sphere. The workflow will be:

1. User prepares a set of files that meet the requirements for text searchable content in SDR ([requirements documentation is on Consul](https://consul.stanford.edu/display/DLSSDOCS/How+to+remediate+previously+OCR%27d+SDR+content+to+enable+text+search))
2. User stages those files for Preassembly
3. User chooses the "Group by filename (with OCR)" option when filling out the Preassembly form
4. Preassembly applies the settings needed to enable text search

The specific settings to be applied are:

- Follow the logic of the "filename" option and group files into resources based on filename
 - For image content type, groups that contain an image should be placed into "image" resources
 - For page content type, groups that contain an image should be placed into "page" resources
 - Any file that does not fit into an "image" or "page" group should be given its own "object" resource
- For any PDF, XML, or TXT file contained in a "page" or "image" resource, apply the following publish/shelve/preserve settings: yes/yes/yes
- For any JPG, TIF, or PNG file contained in a "page" or "image" resource, apply the following publish/shelve/preserve settings: "no/no/yes"
- Additionally, all XML files within "page" or "image" resources should be given the "role" of "transcription"

**Additional context**

The above detailed settings are required in order to enable text search. Preassembly's defaults do not apply these settings. It would be problematic to change Preassembly's defaults to handle the OCR use case because there is no way to determine automatically when a TXT or XML file contains OCR data and when it contains other data, such as TEI XML or processing logs. Adding an explicit option to the menu would enable and require users to specify when an accession contains OCR.

Note also that it's currently possible for users to apply these settings via a file manifest. The challenge with the file manifest is that batches of book objects can contain thousands of files, meaning that a user would need to created thousands of rows in their file manifest CSV. Enabling Preassembly to recognize the established way of processing files with OCR for text search would reduce the burden on users.

**Out of scope**

This ticket is not a request to incorporate the creation of OCR data into the Preassembly/Assembly workflow. It's strictly to ease accessioning for cases where OCR is created before the files are staged for Preassembly. Most SDR items that have OCR are OCR'd through an integration with Goobi. There's a growing interest in accessioning files that have been OCR'd by outside organizations, such as vendors or digitization partners.

**Comment by edsu** [comment]
@andrewjbtw re "there is no way to determine automatically when a TXT or XML file contains OCR data and when it contains other data, such as TEI XML or processing logs" if this is the case then how are we going to know how to index it?

**Comment by andrewjbtw** [comment]
If there's another way to do this, that would be great. I don't have a lot of faith in automated tools getting this right for TXT files. For XML files, I believe there is a header that identifies the ALTO version.

The way this works for the Access apps is that they take the following information from the structural metadata (in the public XML):

- XML/TXT file is published (i.e. listed in the XML)
- XML/TXT file has to be identified with the proper mimetype (for text or XML)
- XML/TXT file is shelved (making it accessible to Access apps)
- XML/TXT file has "role=transcription" (signifying it should be indexed for search)

All of those attributes have to be assigned at accessioning so they're put into the XML because there's no detection of file type or role on the Access side. If we change the derivative/access strategy writ large, there's a lot of room for improvement.

**Comment by ndushay** [comment]
(recording discussion in mtg;  andrew's comment above is a better source)

The user says what it is when they are accessioning their files;  we assume the user has correctly identified OCR files so we can treat them as OCR files and display them as such in the public_xml from the purl page;   then the access team knows what to do to make the OCR files have value (e.g. searchable text, whatever)

There is no testing, validation or checking of the OCR;  the access team just tries to use it for search.
