### ISSUE TITLE
Upload via Globus button

### ISSUE THREAD

**Issue by edsu** [sul-dlss/pre-assembly#1188]
The title for this ticket is deceptively simple. It involves frontend JavaScript work, backend database work, and API interactions.

The page to create a new Project (the home page) should include a button "Request Globus link".  When clicked a new upload directory in the Globus Endpoint should be created for the user, and the user's browser should open a new tab pointed to the Globus File Manager for that directory opened as a new tab in their browser, and the *Staging Location* in the form should be filled in with the URL for the new Globus location.

![Screenshot 2023-08-04 at 3.41.03 PM.png](https://images.zenhubusercontent.com/5deed23289fe1c7c48a2e313/9e95b0ea-0e6b-4174-bb0a-2216b301edfd)

![Screenshot 2023-09-07 at 7 07 36 AM](https://github.com/sul-dlss/pre-assembly/assets/33829/61522446-564c-4a41-87f2-41a6d8ddfe8f)

The logic for creating the upload directory is similar to [what is in H2](https://github.com/sul-dlss/happy-heron/blob/main/app/jobs/globus_setup_job.rb#L35-L46) but we are going to handle the request synchronously (not part of a Sidekiq job), and we are going to use a timestamp instead of a Work ID for the directory.

When a user clicks *Request Globus link*:

1. An HTTP POST to the server will be sent indicating the user wants a Globus directory.
2. The receiving Rails controller will create a new `GlobusDestination` (a new AR model) that records the `user_id`, `created_at` and `deleted_at` (which is null).
3. The controller will create the Globus upload directory for the user using `GlobusClient.mkdir` with a `path` of `/{sunet}/{GlobusDestination.created_at}/}`. The `GlobusClient` should be configured using Settings similar to [what is in H2](https://github.com/sul-dlss/happy-heron/blob/main/config/settings.yml#L10-L14).
4. The Rails controller will tell the browser to update the *Staging Location* input box with the URL for the new Globus endpoint, e.g. https://app.globus.org/file-manager?&destination_id=f3e29605-7ba5-45f5-8900-f721663cf1af&destination_path=/edsu/20230907044801/, and will also open a new tab pointed at the Globus File Manager for the new folder.  It may be useful to add a `GlobusDestination.url`, `GlobusDestination.destination_path` and `GlobusDestination.staging_location` helper methods to isolate the logic for these.

When the user finally submits the form to create the new Project aka BatchContext, it is linked (one-to-one) with the appropriate `GlobusDestination`. The controller will need to be adjusted to be able to: 

1. Allow for the form field to be a Globus URL
2. Use the `destination_path` in the Globus URL and the current user to look up a `GlobusDestination` object.
3. Set the `BatchContext.staging_location` to the full path to the staging location on the server (using a `GlobusDestination.staging_location` helper method).
4. Persist the new `BatchContext` and updated `GlobusDestination`
5. Continue JobRun as normal

To prevent unintentional creation of too many access points (Globus imposes a max of 100) if the user has 99 active GlobusDestination records associated with their account (`deleted_at` = nil) the button will be disabled and an error message will be displayed: 

![Screenshot 2023-09-05 at 12 08 41 PM](https://github.com/sul-dlss/pre-assembly/assets/33829/d7b22d37-da28-44ce-8464-e79e2a6b6355)

The message should read "You have too many active please email SDR Manager for help" which links to an email alias for the SDR manager.

The deletion of access rules will be handled in #1189. The use of access rules to manage access will allow us to be able to mark a directory as processed, which can aid in deleting data from the preassembly mounts in the future.

**Comment by andrewjbtw** [comment]
Astrid's design with a "Request Globus link" button on the right:

![Screenshot 2023-08-04 at 3.41.03 PM.png](https://images.zenhubusercontent.com/5deed23289fe1c7c48a2e313/9e95b0ea-0e6b-4174-bb0a-2216b301edfd)

https://projects.invisionapp.com/share/K3139Q9BDJ8H#/screens/473632153_preassembly

**Comment by andrewjbtw** [comment]
I like the idea of taking the user to the Globus space rather than emailing the link. The next step will be to add the files, so they won't be ready to fill out the Preassembly form at this point.

**Comment by edsu** [comment]
@astridu I think we need to consider how to let the user know when they have requested too many Globus links.

**Comment by astridu** [comment]
https://invis.io/KT13BSZ94RP3#/474490224_preassembly_Globus_Link_Error

**Comment by justinlittman** [comment]
A few questions:
1. Is a GlobusDestination associated with a BatchContext?
2. How does a user remove a globus destination? (That is, they clicked the button by now changed their mind.) How does a removed globus destination get cleaned up?
3. How will you know when a user is done creating JobRuns for a BatchContext, so that you know when to delete the access rule?
4. If the user clicked the button multiple times, can a BatchContext have multiple globus destinations?

**Comment by edsu** [comment]
Re 1: Yes

"When the user finally submits the form to create the new Project aka BatchContext, it is linked (one-to-one) with the appropriate `GlobusDestination`."

Re 2: This might be a good thing to keep in mind for #1189?

Re 3: I think #1189 addresses this now?

Re 4: No, BatchContext and GlobusDestination are one-to-one

**Comment by andrewjbtw** [comment]
Some of this, particularly scenario 4, is going to need further discussion. In the current design, the BatchContext is not going to exist when the user clicks the button. The association will only be made between a BatchContext and a Globus location when the user actually fills out the form later and pastes in the Globus URL. So someone clicking multiple times will get multiple Globus destinations but none of them will be associated with a BatchContext until they create one by filling out the form.

We may need to take another look at the multiple clicks situation. A user might want to prep multiple different batches and need multiple different Globus locations. But we could also end up with Globus locations that never get used.

**Comment by edsu** [comment]
Based on the storytime earlier today I'm going to adjust this ticket to reflect the original design of allowing the Globus URL to be pasted into the form to create a new BatchContext.

**Comment by lwrubel** [comment]
Will be working next on setting up helper methods on the GlobusDestination model and specs.

**Comment by edsu** [comment]
I'm going to start looking at changes in the controller to accept the POST to create the GlobusDestination

**Comment by lwrubel** [comment]
There should be some validation of the globus URL that is put in the staging location field in the batch context form. Would go on form submit?

**Comment by edsu** [comment]
Yes, I think it will have to be handled in the controller that creates the new BatchContext. I'm getting closer to working my way to that...
