### ISSUE TITLE
Cron job to delete Globus access rule when accessioning completed successfully

### ISSUE THREAD

**Issue by edsu** [sul-dlss/pre-assembly#1189]
Once a Project using a Globus endpoint has completed successfully the Globus access rule should be deleted as in H2:

https://github.com/sul-dlss/happy-heron/blob/79c258bbfe455ddbdf56c16a55901021a56fb805/app/services/work_observer.rb#L48

If access rules are not deleted they can cause the creation of new ones to fail. This will not delete the data in the Globus upload directory, but will prevent further access to it.

Deletion doesn't need to be done as soon as the Project is completed--given how Preassembly works it's not exactly clear when users are actually done. But we can do it periodically as a daily cron job (using [whenever](https://github.com/javan/whenever) or whatever the best way to do cron jobs in Rails is now).

We would like to delete access rules that are older than 1 week for which there is a completed preaccessioning job. 

The logic for identifying Access Rules in need of deletion is to find any `GlobusDestination` where:

* the `GlobusDestination` was created at least 1 week ago
* the `GlobusDestination` has not already been deleted (`deleted_at = nil`)
* the `BatchContext` associated with the `GlobusDestination` has a `JobRun` that is in the state `accessioning_complete`

For each identified `GlobusDestination`:

* Use the `GlobusClient.delete_access_rule` to delete the access rule (using the `GlobusDestination.user` and `GlobusDestination.destination_path`).
* Update the `GlobusDestination.deleted_at` to the current time.
* Write a log message about the deletion.

**Comment by mjgiarlo** [comment]
This ticket is blocked by #1188 because it needs the GlobusDestination model.

**Comment by justinlittman** [comment]
@edsu GlobusDestinations are associated with BatchContexts not JobRuns. JobRuns can be completed, but not BatchContexts. How should this work?

**Comment by edsu** [comment]
Thanks @justinlittman the lay of the land has changed since this ticket was created. I will update the description.

**Comment by edsu** [comment]
Ok, the description has been updated. It actually might be good for @andrewjbtw to take a look at this to make sure it looks good.

**Comment by andrewjbtw** [comment]
I think the logic for identifying completed deposits should be separate from the logic for identifying unused Globus spaces. I would give people more than two weeks to prepare their deposits.

For identifying completed deposits, I think the logic makes sense. A successful JobRun connected to a BatchContext should mean that all the items were accessioned. 

A BatchContext is also associated with a single progress YML log, which should eventually show that all druids were accessioned. I'm not sure if checking the druids in that file would add anything beyond checking the JobRun statuses.

**Comment by edsu** [comment]
Ok, I will remove the part of the description that involves removing dangling `GlobusDestination`s (Globus directories that have not been used). 

Is two weeks or older a reasonable limit for cleaning up `GlobusDestination`s whose associated `BachContext` (Project) are completed?

**Comment by andrewjbtw** [comment]
Let's shorten it to one week for a successful job.
