### ISSUE TITLE
Mark endpoint as read-only once submitted to DSA

### ISSUE THREAD

**Issue by edsu** [sul-dlss/pre-assembly#1190]
When a Globus endpoint is used to submit a deposit to dor-services-app the endpoint should be marked read-only to prevent other files from landing or being modified while the accessioning is running. 

See disallow_writes in H2 for an example of this:

https://github.com/sul-dlss/happy-heron/blob/79c258bbfe455ddbdf56c16a55901021a56fb805/app/jobs/deposit_job.rb#L37-L43

Ideally this should be implemented as an asynchronous sidekiq job so it can be retried when Globus is not available, without requiring another deposit.

**Comment by edsu** [comment]
Can we still mark a Globus endpoint read-only if we want to allow users to re-run Projects in cases where one-or-more objects in a batch fail accessioning? They would most likely need to change files on the filesystem to fix the problem right? 

I think knowing when to mark a filesystem read-write depends on knowing when an error has happened (see #1225):

1. We could have a button to "unlock" the Globus endpoint on the Project page when the last JobRun is in an Error state?
2. We could automatically mark the endpoint read-write once a JobRun results in an error.

**Comment by andrewjbtw** [comment]
These are good questions that I hadn't thought about with Globus. We don't currently protect any staging source for preassembly from data being modified while preassembly is running.

**Comment by edsu** [comment]
@andrewjbtw I'm going to close this issue, and we will continue to trust users not to play with the files while they are in flight. If it proves to be a problem we can revisit.
