### ISSUE TITLE
Job detail page improvements

### ISSUE THREAD

**Issue by edsu** [sul-dlss/pre-assembly#1193]
The page for  a job currently requires clicking a button to see the Details. This button should be removed and the details should always be displayed.

New design: https://projects.invisionapp.com/share/KT13BSZ94RP3#/screens/474449085

![Screenshot 2023-08-04 at 12 50 13 PM](https://github.com/sul-dlss/pre-assembly/assets/33829/7d697b38-4adf-4220-9ecb-3f57ed9624e4)

![Screenshot 2023-08-04 at 12 51 36 PM](https://github.com/sul-dlss/pre-assembly/assets/33829/352ff78d-062c-4435-b1bf-e31c1ab97a11)

The separate tables should be integrated so that they align, use available whitespace, and are easy to read.

If the job is a discovery report this information the "view summary in browser" link should be removed and the information should always be provided: e.g. see https://sul-preassembly-prod.stanford.edu/job_runs/11521

The discovery report table should be expanded so that that rows don't have needless line breaks:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc1pRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6f741df0cff3a03c0998de0b3796598ed9defff0/Screenshot%202023-08-30%20at%207.11.57%20AM.png)

**Comment by ndushay** [comment]
Ed:  so is this ticket to implement Astrid's new design, or to do the simpler change?  If the latter, is there a ticket to implement Astrid's design?

**Comment by andrewjbtw** [comment]
@peetucket This is the design that uses the existing discovery report output: https://projects.invisionapp.com/share/KT13BSZ94RP3#/screens/474449085

The link currently in the ticket description shows the file diff (or whatever we call it).
