### ISSUE TITLE
"StructuralDiff" service

### ISSUE THREAD

**Issue by edsu** [sul-dlss/pre-assembly#1195]
Create (or reuse) a service (you can change the name if you want) which accepts:

* a DRUID (or a Cocina Object)
* a pre-assembly file path for the staging location

The service should look for a *File Inventory*  CSV file in the staging location, and compare its contents, and the files in the staging location, with the latest version of structural metadata. The result should be an `StructuralDiffReport` object that records the *ADD*s, *UPDATE*s and *DELETE*s that would be preformed. The `PreAssembly::FileManifest` class should be used to work with the File Manifest.

* An *ADD* is a file that is present in the CSV, and on the filesystem, but not in Cocina.
* A *DELETE* is a file that is not present in the CSV, but is in the Cocina.
* A *UPDATE* is a file that is present in the spreadsheet and on the filesystem

The report object should have to/from JSON methods for serializing and deserializing the results from the Job JSON so it doesn't need to be run every time the Job detail page is viewed.

This service will need to be invoked during Discovery and Preassembly job runs in `PreAssembly::Batch`.

Note: One approach to this might be to create Cocina Structural for the staging location, and then reuse code for comparing two Cocina Structural objects.

**Comment by ndushay** [comment]
naming suggestions from storytime:
- ObjectFilesDiff
- DROFilesDiff 

...

**Comment by ndushay** [comment]
from storytime chat:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdVZVIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8526f72a180b38792421cbac6febc4d9e8097edd/image.png)

**Comment by ndushay** [comment]
from storytime:  

This ticket has to consider hierarchical file structure as well.
