### ISSUE TITLE
Enable Globus in all environments

### ISSUE THREAD

**Issue by edsu** [sul-dlss/pre-assembly#1200]
The Globus attached storage needs to be add to `/globus` on:

* sul-preassembly-prod.stanford.edu
* sul-preassembly-qa.stanford.edu
* sul-preassembly-stage.stanford.edu

It should be mounted read/write for user `preassembly` so that sidekiq workers can interact with it. This is potentially a security problem because some users who have access to the `preassembly` user for copying files will potentially be able to see the `/globus` directory. However the hope is that sftp and ssh access to these machines will be turned off once Globus integration is complete.

**Comment by justinlittman** [comment]
See https://github.com/sul-dlss/operations-tasks/issues/3457

**Comment by justinlittman** [comment]
See https://github.com/sul-dlss/operations-tasks/issues/3457#issuecomment-1716660135
