### ISSUE TITLE
Sidekiq job to mark JobRun as complete

### ISSUE THREAD

**Issue by edsu** [sul-dlss/pre-assembly#1201]
Once a queue has been enabled in #1199 pre-assembly will get notified when an object has completed accessioning. We need a Sidekiq job that will listen to this queue and will transition the `JobRun` state from *Preassembly Complete* to a new state *Accessioning Complete*. A similar example of listening to the queue can be found in: 

https://github.com/sul-dlss/happy-heron/blob/main/app/jobs/deposit_complete_job.rb

A new `EndAccession` service should be created that contains the logic for marking a `JobRun` as complete. Some important things to keep in mind:

- a `JobRun` can start the accessioning of multiple SDR objects
- the RabbitMQ message indicates when a specific DRUID has cleared accessioning
- the SDR object that has cleared accessioning may not be related to activity in Preassembly

So when receiving a DRUID the logic for marking a job as complete is as follows:

1. get the Cocina for the object
2. get the latest version
3. look for an `Accession` object for the *druid* and *version* where *completed* is nil
4. log a message that the Accession wasn't found and stop if no Accession is found
5. mark the `Accession` as completed
6. see if all the `Accession` objects associated with the `JobRun` are completed, if they are send the `JobRun` state machine the `accessioning_completed` event.
7. Update the Job listing on the BatchRun aka "Project" view to indicate that the Job is complete (see #1231)

**Comment by justinlittman** [comment]
1. How is an item associated with a JobRun (such that it is known which JobRun a notification applies to)?
2. A JobRun can be associated with multiple items, correct?
