### ISSUE TITLE
Show accessioning workflow info for a Pre-Assembly Run job

### ISSUE THREAD

**Issue by edsu** [sul-dlss/pre-assembly#1202]
[This ticket has been updated following conversations with @astridu - Andrew]

When viewing a Pre-Assembly Run JobRun in the UI, it would be helpful to see information about the one or more objects that will be updated as part of the run, and whether they have been completed.  This information can be presented in a table that includes:

* *druid*: the DRUID for an object being updated, which links to the view in Argo
* *status*: the current state of the druid with respect to the current Preassembly job run

<img width="945" alt="Screenshot 2023-10-03 at 12 26 26 PM" src="https://github.com/sul-dlss/pre-assembly/assets/8975583/3e7dea13-2165-4713-a85b-c8a2618b8900">

https://projects.invisionapp.com/share/KT13BSZ94RP3#/screens/474787731

The statuses should be based on data Preassembly tracks in order to send emails:

- In progress: druid has either not started processing or is still in process (every druid starts at "In progress")
- Preassembly error: druid encountered an error in Preassembly
   - This is the state that triggers the Preassembly error email
- Accessioning error: druid encountered an error in accessioning
   - This is the state that leads a druid to be listed in the "these druids hit an error" section of the Job completed email
- Accessioning success: druid completed accessioning successfully

In terms of errors, we should display more information if available or link out to Argo for details:

- Preassembly error: this should result in a message in the Preassembly log, which should be displayed in the table
- Accessioning error: I don't think Preassembly tracks this error in detail, so instead, provide link to Argo

In terms of scope: the status reporting should be based on the specific Job Run. If an error is fixed, and a druid completes accessioning, it's ok to update the status on the Job Run page. But it's not strictly necessary to update the page. Preassembly should also not act on messages that come from subsequent activity for druids if that activity originates elsewhere, such as Argo.

**Comment by edsu** [comment]
@astridu if you have time to think about how this should look that would be appreciated!

**Comment by astridu** [comment]
https://invis.io/KT13BSZ94RP3#/474449085_Discovery_Report_-_Errors

**Comment by edsu** [comment]
@astridu I was hoping for a table that listed the objects that are being updated one by one, when accessioning started for them, and when it completed. This table lets a user know how complete their batch job is. Maybe this can be worked into an existing table, or perhaps it needs to be a new table?

**Comment by astridu** [comment]
Sorry, that was the wrong screenshot:

https://invis.io/KT13BSZ94RP3#/474490150_1231

**Comment by mjgiarlo** [comment]
@andrewjbtw and @astridu will chat to pin down the needed design.

**Comment by ndushay** [comment]
Andrew needs to update per discussion they had last thursday.

**Comment by edsu** [comment]
@andrewjbtw is this something we still want to try to get done in this work-cycle?

**Comment by andrewjbtw** [comment]
I've updated the ticket with requirements and Astrid's new design.

**Comment by justinlittman** [comment]
How should batches with a large number of items be handled?

**Comment by andrewjbtw** [comment]
Could we paginate the display?

**Comment by justinlittman** [comment]
Per discussion on 10-4: Because of difficulties performing pagination for both preassembly errors and accessions, not going to perform pagination. However, the progress log should be rendered in a turbo-frame.
