### ISSUE TITLE
EPIC: Require Discovery Report

### ISSUE THREAD

**Issue by edsu** [sul-dlss/pre-assembly#1212]
Currently users can optionally run a discovery report on their batch load to see if everything is set up correctly. Since we are enabling updates to repository objects using partial files on the file system we would like to *always* require a successful discovery report in order to start a job.

**Comment by andrewjbtw** [comment]
Putting this out of scope for the Fall 2023 workcycle. There are a few use cases where users need to ignore discovery report errors and we will not be able to address those within this workcycle.

**Comment by edsu** [comment]
Should we close the tickets? Maybe thinking about this will change when/if we revisit?

**Comment by mjgiarlo** [comment]
This is not currently in scope, and we're opting to close this epic and re-write / re-think this work when we prioritize it eventually.
