### ISSUE TITLE
Projects or Batches?

### ISSUE THREAD

**Issue by edsu** [sul-dlss/pre-assembly#1215]
The user interface talks about Pre Assembly Projects, but underneath they are modeled as a *BatchContext* which have one or more *JobRun* objects associated with them. Does it make sense to talk about "Batches" in the user interface rather than "Projects"?

**Comment by edsu** [comment]
I think the answer is that Project better matches how users are using BatchContexts. They get reused over time.

```
SELECT COUNT(*), MAX(created_at) - MIN(created_at) AS batch_use_time
FROM job_runs
WHERE state = 'complete'
GROUP BY Batch_context_id
ORDER BY batch_use_time DESC
```

[preassembly-jobs.csv](https://github.com/sul-dlss/pre-assembly/files/12441655/preassembly-jobs.csv)

**Comment by edsu** [comment]
I'm reopening because a project can only be run once successfully:

```sql
SELECT COUNT(*), MAX(created_at) - MIN(created_at) AS batch_use_time
FROM job_runs
WHERE state = 'complete'
  AND job_type = 1
GROUP BY Batch_context_id
ORDER BY batch_use_time DESC
```

[preassembly-jobs.csv](https://github.com/sul-dlss/pre-assembly/files/12442466/preassembly-jobs.csv)

**Comment by mjgiarlo** [comment]
Ed is in favor of closing this.
