### ISSUE TITLE
Model relationship between JobRun and SDR items

### ISSUE THREAD

**Issue by edsu** [sul-dlss/pre-assembly#1219]
In order to mark a `JobRun` as complete when SDR accessioning is complete #1201 we need to know what repository items are associated with which JobRuns.  To do this a new ActiveRecord model named `Accession` will be added that is in a zero-to-many relationship with `JobRun`. A given `JobRun` may have zero-to-many `Accession` objects associated with it.

The `Accession` object should have these properties:

- *created*: the datetime the accession was created
- *druid*: the druid that is being accessioned
- *version*: the version of the object that is being created by the accessioning
- *completed*: the datetime that the accession object was marked completed (see #1201)

The creation of an `Accession` object should be dependent on successfully starting accessioning in the `StartAccession` service.

**Comment by justinlittman** [comment]
"Accession" is a new term. Should be use an existing term like "Dro" or "Cocina item"?

AR objects will already have a "created_at" attribute that is set when the db row is created. Does that cover the "created" attribute?

Also, should the "completed" attribute by "completed_at" to be consistent with AR naming conventions?
