### ISSUE TITLE
Send email when accessioning complete or results in errors

### ISSUE THREAD

**Issue by edsu** [sul-dlss/pre-assembly#1220]
Currently users get an email when their Job has completed preaccessioning. Now that we know when an object finished accessioning (see #1201) we can let users know when their job has cleared accessioning instead. This will prevent situations where a user sees a completion email when the object actually errored durig accessioning.

Since we also know what DRUIDs were accessioned (see #1219) we can also include in the body of the email which DRUIDs have completed, with links to Argo.

```
Dear {user},

Your Preassembly job {link-to-preassembly-job} has successfully accessioned the following SDR objects:

- https://argo.stanford.edu/view/druid:123
- https://argo.stanford.edu/view/druid:456
- https://argo.stanford.edu/view/druid:789

The following SDR items failed accessioning:

- https://argo.stanford.edu/view/druid:000
```

**Comment by justinlittman** [comment]
Is this email supposed to be sent when all of the DROs for a job have completed accessioning?

**Comment by mjgiarlo** [comment]
@justinlittman Yes.

**Comment by edsu** [comment]
I'm pinging @andrewjbtw on this since he wants to craft the text of the email a bit.

**Comment by ndushay** [comment]
see also #1261????

**Comment by mjgiarlo** [comment]
@aaron-collier Are you actively working on this or is it hanging out a while?

**Comment by aaron-collier** [comment]
@mjgiarlo yeah, slowly in between other work. should have a PR today.

**Comment by andrewjbtw** [comment]
I tested this and it was not successful, so I'm re-opening it. I never got an email.

**Comment by andrewjbtw** [comment]
For the failure, here is the:

- [preassembly job](https://sul-preassembly-qa.stanford.edu/job_runs/945)
- [Argo view of the four druids in the job](https://sul-preassembly-qa.stanford.edu/job_runs/945), with one error

I'd have expected a message that 3 druids succeeded, one hit an error in accessioning.

**Comment by andrewjbtw** [comment]
No email received for a fully successful job either:

- [preassembly job](https://sul-preassembly-qa.stanford.edu/job_runs/947)
- [Argo view for the two druids that were accessioned](https://argo-qa.stanford.edu/catalog?f%5Bexploded_tag_ssim%5D%5B%5D=Project+%3A+emails&f%5Bexploded_tag_ssim%5D%5B%5D=Project+%3A+emails+%3A+expect+success)

**Comment by jmartin-sul** [comment]
apologies if i merged the PR early and closed this before i should've.  didn't see a [HOLD] in the PR title, so seemed ok to merge.
