### ISSUE TITLE
Targeted file update integration test

### ISSUE THREAD

**Issue by edsu** [sul-dlss/pre-assembly#1230]
The targeted file updates require a user to use a CSV to control how an SDR item is accessioned, and impacts several other SDR systems. Once we have completed the targeted file update functionlity it would be useful to have an integration test that creates a new version of an SDR item (adding, updating and deleting files) and ensures that it makes it through accessioning correctly and appears correct in Argo and/or DSA.

**Comment by ndushay** [comment]
Is this now done?
