### ISSUE TITLE
Project view should display JobsRuns

### ISSUE THREAD

**Issue by edsu** [sul-dlss/pre-assembly#1231]
Currently the `BatchContext` a.k.a. Project view e.g. https://sul-preassembly-prod.stanford.edu/batch_contexts/1400 displays simple information about a Project, but doesn't let you view its `JobRun`s. 

When a `BatchContext` has associated `JobRun`s they should be presented in a table listing:

* *JobRun ID*: which links to the detail for JobRun
* *User*: the user who ran the job
* *Type*: discovery report or pre-assembly run
* *Created*: when the job was created

I think this should be fairly straightforward but if @astridu has design ideas for this they would be welcome!

**Comment by astridu** [comment]
https://invis.io/KT13BSZ94RP3#/474490150_1231

**Comment by edsu** [comment]
> https://invis.io/KT13BSZ94RP3#/474490150_1231

Thanks @astridu -- a Project an have multiple job runs associated with it. It seems like your design would only accommodate one?

**Comment by peetucket** [comment]
Yup, the details section could be a table below, with one row per job run (and columns for each piece of data we have about the job run).  The job runs could be linked to the job run detail page (which is being reworked in a different PR).

**Comment by peetucket** [comment]
Note: I wonder if we want to unblock this -- we can implement the new view even without the notification for when accessioning is done and then just add that column in later when it's available (i.e. disconnect from #1201 but add a note that ticket to show status in this page when available).

**Comment by edsu** [comment]
Good idea @peetucket. I've updated #1201 to mention the additional work to add the Accessioning Complete status to the view component that will be created by this task.
