### ISSUE TITLE
Discovery report should show error when more files are staged than listed in the file manifest

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/pre-assembly#1233]
Preassembly has an error condition for jobs with a file manifest we describe as:

>files_found_mismatch
>
>The number of files in the manifest does not match the number of files found in the object folder.
([see our list of possible errors](https://github.com/sul-dlss/pre-assembly/wiki/Explanation-of-possible-errors-in-a-discovery-report#files_found_mismatch))

As described, the error should occur whenever the number of files stage on the staging filesystem does not match the number of files listed in the file manifest.

In testing, I found that:

- Preassembly would detect when files on the manifest were not staged on the filesystem
- Preassembly would not detect when files staged on the filesystem were not listed on the manifest

Additional testing revealed two potential complications:

- MD5 sidecar files that should not be part of the cocina
- "hidden" files, which seem to be dotfiles (not the Windows definition of hidden files, AFAIK)

The discovery report should ignore these files if they are present but not listed on the manifest.

**Expected behavior**

The discovery report should report a files_found_mismatch when files are staged that are not on the file_manifest.csv UNLESS

- the files are sidecar MD5 files (there should be an indication of how these are defined for checksum checking purposes in assemblyWF)
- the files are hidden files

If someone does list an MD5 file on the file_manifest.csv, that should not trigger an error as long as the file is either staged or already present in a previous version of the object.

**Comment by justinlittman** [comment]
@andrewjbtw The logic in the code only reports an error when there are files in the manifest that are not found on disk. Are you sure that there aren't cases in which there are files on disk (e.g., the .md5 files or similar) that are deliberately not included in the manifest?

(I'm asking because the code seems quite intentional in not checking for extra files on disk for this error, rather than being an accidental omission.)

**Comment by andrewjbtw** [comment]
Good catch. I don't think the sidecar MD5 files go on the manifest but I'm not sure. I'll have to do some testing of what happens. I found that Preassembly would copy only the files listed on the manifest and ignore the others. I didn't try with MD5 files, which might get "special" treatment.

**Comment by peetucket** [comment]
Yes, I picked this up but will pause.  Justin has a good point.  It's possible if we implement this check, we'll want to add some "exclusions", else you might get failures due to extra files you really don't care about (like hidden Mac files, MD5 files, etc.)

**Comment by justinlittman** [comment]
I also wonder if content created by vendors will have other cruft that should be ignored.

Maybe discovery report should just list the files instead of treating as an error?

**Comment by andrewjbtw** [comment]
I've done some testing of existing behavior. I'll post the results below but I think we should hold off on changing this logic until after the targeted file updates work because that will also involve changing file_manifest validation logic.

# Current behavior:

## Using sidecar md5 files

Sidecar md5 files are files that use a naming convention where a ".md5" is tacked on to the name of a file in the accession:

accessioned_file.txt
accessioned_file.txt.md5

- if md5 files are present but not in file_manifest:
 - the md5 values are validated at checksum-compute but the .md5 files are not accessioned
- if md5 files are present and listed in the file_manifest:
 - the md5 files are accessioned with the other files
- if md5 files are present and there's no file_manifest (just the manifest.csv is used)
 - md5 files get accessioned with the other files

I take that as confirmation that the original implementation of sidecar md5 files is built around having the files present but not in the file_manifest.csv. That's the only way to avoid accessioning the .md5 files. Since we don't want these sidecar files in the accession, we need a way to preserve this behavior.

## testing hidden files

Since I'm on a Mac, I'm taking hidden files to mean any file starting with ".". I tried a few patterns:

- .DS_Store
- .hidden
- .a_hidden_file

In this case, the discovery report never "found" the hidden file, meaning that the counts of files found and the list of mimetypes found did not include the hidden files. As far as I can tell, the result is that it's effectively impossible to accession hidden files. Maybe Windows hidden files would be treated differently once staged on a Linux filesystem.

With a file manifest, listing the hidden files on the manifest leads to a discovery report error since the discovery report job never finds the hidden files, resulting in a mismatch between number of files found and number of files listed. That's always an **undercount**, so not directly relevant to this ticket, which is about having more files than on the manifest.

Leaving the hidden files off the file_manifest is not a problem in the current implementation as that doesn't cause a mismatch between files found and files listed.

**Comment by mjgiarlo** [comment]
Waiting on targeted file updates.

**Comment by ndushay** [comment]
waiting for targeted file updates to settle because there was a problem with the original file manifest;  this may ultimately be unsolvable???

**Comment by edsu** [comment]
Since all the remaining targeted file update work is now complete, I'm moving it to ready for consideration again.

**Comment by edsu** [comment]
From Planning: The action that we need to take needs to be added to the ticket, now that the rest of the targeted file update work is done.

**Comment by andrewjbtw** [comment]
I've updated the ticket with details on how to handle sidecar MD5 files and hidden files.
