### ISSUE TITLE
Sidekiq job to mark a JobRun as error

### ISSUE THREAD

**Issue by edsu** [sul-dlss/pre-assembly#1241]
Similar to the work done in #1199 we need Preassembly to listen for Accessioning errors. Perhaps it makes sense to have one Sidekiq job that listens for both types of messages? Or maybe we need two Sidekiq jobs? When Preassembly receives a message that a particular DRUID has encountered an error it needs to:

0. Listen to Rabbit for `*.error` messages on the `sdr.workflow` topic (for the `*` notation see [the docs](https://www.rabbitmq.com/tutorials/tutorial-five-ruby.html))
1. Look for the first `Accession` model that matches the DRUID, where `completed_at` and `errored_at` are nil, ordered by version descending.
2. Fetch the Cocina for the DRUID
3. If the version matches update the `Accession.errored_at` to the current time.
4. Look at the `JobRun` that the `Accession` is attached to. If all of the`Accession` objects are either complete or in an error state transition it into a `:completed_with_errors` state.

**Comment by justinlittman** [comment]
To simplify steps 1-3, I'd suggest adding the version to the workflow message here: https://github.com/sul-dlss/workflow-server-rails/blob/main/app/services/send_rabbitmq_message.rb#L17

**Comment by mjgiarlo** [comment]
J-Litt thinks this may be done.

**Comment by mjgiarlo** [comment]
#1239 closed this.

**Comment by edsu** [comment]
This work does look done: https://github.com/sul-dlss/pre-assembly/blob/main/app/jobs/accession_complete_job.rb#L25-L28
