### ISSUE TITLE
Don't show the BatchContext progress log on the individual job run pages

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/pre-assembly#1266]
A "progress log" is now appearing at the bottom of every job run page that shows the results of each of the jobs that have been run for that BatchContext. I'm finding this very confusing because I'm only looking for information about a single job when I'm on a job run page. To get information about the BatchContext, I'd click on the link to the BatchContext.

Beyond the problem of seeing the log for the whole BatchContext, the "Progress log" doesn't even show the progress of the job run while the job is running. In the screenshot below, the Progress log shows the results of previous runs but the job run I'm looking at is still in progress. I think it would be simpler to not show the progress log on a job run page than to show a different progress log on job run pages vs BatchContext pages.

<img width="1409" alt="Screenshot 2023-09-15 at 9 26 31 AM" src="https://github.com/sul-dlss/pre-assembly/assets/8975583/badb7050-aaa7-4ce1-bb39-8c3543083b1a">

**Comment by peetucket** [comment]
Should we show the progress log file on the batch context detail page instead?

FYI: the reason it doesn't show what's happening with a job currently running is that it loads the file when the page first loads and then shows the results. If you were to refresh the page, it would load again and update with new rows.
