### ISSUE TITLE
Don't show lists of job runs together on the same page as the long lists of batch_contexts

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/pre-assembly#1268]
Preassembly has a list of all "Projects" (BatchContexts). That list is now showing not just each of the BatchContexts but all of the job runs for those projects (under the "jobs summary" heading). I think it would be easier to read those pages if the list just showed the BatchContexts and left the job summaries for the BatchContext pages.

<img width="1358" alt="Screenshot 2023-09-15 at 10 31 10 AM" src="https://github.com/sul-dlss/pre-assembly/assets/8975583/e5deffa8-b04c-4620-9666-8db3d0c47dbb">

**Comment by peetucket** [comment]
Another suggestion: make the list of batch contexts a table, which will be much more compact.
