### ISSUE TITLE
Changes made to discovery reports in an earlier PR seem to have disappeared from the UI

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/pre-assembly#1283]
**Describe the bug**
PR https://github.com/sul-dlss/pre-assembly/pull/1238 introduced changes to discovery reports to support targeted file updates. I thought that change had been merged and the PR is closed. However, the Preassembly UI is not showing the new UI.

This ticket is to figure out what happened. 

The original ticket for the UI changes is https://github.com/sul-dlss/pre-assembly/issues/1196 and has been closed. We could reopen if need be.

**Comment by edsu** [comment]
I think this is a defect introduced by our move to turbo frames for the discovery report? The `@structural_has_changed` value appears to be `false` in a view like: https://sul-preassembly-qa.stanford.edu/job_runs/877

See: https://github.com/sul-dlss/pre-assembly/pull/1238/files#r1330749573

**Comment by peetucket** [comment]
Related to my turbo work as Ed suspected, easy fix available now: #1285
