### ISSUE TITLE
Rake task to remove unused Globus Access Rules for a user

### ISSUE THREAD

**Issue by edsu** [sul-dlss/pre-assembly#1287]
When a `JobRun` completes successfully the Globus Access Rule for the staging location is removed after 2 weeks (see #1189). However it's possible that a user could create multiple Globus Access Rules by clicking the "Request Globus Link" button many times, and then not using them. This will result in clutter on the file system, and will eventually lock the user out of creating new Globus Access Rules.

When the user is prevented from creating new Globus Access Rules they will be given an error message with an email link to contact the SDR Repository Manager. The idea is that the SDR Repository Manager could run, or delegate to a developer, the running of a rake task that would remove unused Globus Access Rules for that user:

```
$ bin/rake globus:prune_access[edsu]
```

This would:

1. Find all the`GlobusDestination` objects where user is `edsu` and `deleted_at` is `nil`.
2. Use the `GlobusClient.delete_access_rule` to delete the access rule.
3. Update the `GlobusDestination.deleted_at` to the current time.
4. Print out a diagnostic message about the `BatchContext` associated with the `GlobusDestination` that was marked as deleted.
5. If the staging location is complete empty, remove it from the filesystem.

Once added this new functionality should be documented in the wiki.

**Comment by lwrubel** [comment]
The description says that the task should reduce filesystem clutter, but the way I read the steps, the intent is to remove the globus access rule that gives the user access. The directories and files would stay on globus as they are. Is there a need to delete the directories themselves as well?

**Comment by andrewjbtw** [comment]
I'm wondering how we can define "unused"? What if we limit this scope only to locations that are empty? In that case, I'd be comfortable deleting the location too.

There's an in-between case where someone creates a Globus space and adds data but doesn't complete a deposit. That's not exactly an unused space and in that case I'd have to check with the user before deleting data.

**Comment by edsu** [comment]
I will add a last step to clean up the directory if it is empty.

**Comment by lwrubel** [comment]
I'm not sure what the diagnostic message regarding the `BatchContext` should be in order to be useful. Provide the id of a BatchContext if there is one associated with the `GlobusDestination`? I think in the case where the directory is empty, there probably won't have been a `BatchContext` ever created.

**Comment by edsu** [comment]
@lwrubel That's a good point that the BatchContext not necessarily being present. I think what you have is perfect!

https://github.com/sul-dlss/pre-assembly/blob/fff4ee99851179c8c5fe382f69afe4bf35c0e596/lib/tasks/globus.rake#L12
