### ISSUE TITLE
modify discovery report logic to account for targeted file updates

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/pre-assembly#1302]
When Preassembly is run with a file manifest, the discovery report checks the staging location for every file listed in the manifest. If any file listed in the manifest is not found in the staging area, the discovery report reports that as an error. This made sense when there was a hard requirement to stage every file every time Preassembly was run.

In the new world of targeted file updates, users are no longer required to stage every file. This means that under the current logic, the discovery report will report that files are missing every time someone submits only new or modified files. 

To account for this change, the logic for reporting missing files should be to check for every file in the file manifest in either:

- the staging location OR
- the Cocina for the existing version

If a file is listed in the file manifest and cannot be found in:

- the staging location OR
- the existing Cocina

report that as "[missing files](https://github.com/sul-dlss/pre-assembly/wiki/Explanation-of-possible-errors-in-a-discovery-report#missing_files)" in the discovery report.

If all the files can be found in either

- the staging location OR
- the existing Cocina

do not report that files are missing. The files in the staging location will be sent through accessioning and become part of the new version. The files in the existing Cocina will remain the same.

**Comment by justinlittman** [comment]
If I'm reading the code correctly, this should currently be producing a "files_found_mismatch" instead of "missing files". Does that sound correct @andrewjbtw?

**Comment by andrewjbtw** [comment]
Looks like there are two cases:

Some files staged --> "files_found_mismatch" ([example](https://sul-preassembly-qa.stanford.edu/job_runs/892))
No files staged --> "missing files" ([example](https://sul-preassembly-qa.stanford.edu/job_runs/888))

So you're right "files_found_mismatch" is going to be the more common case.
