### ISSUE TITLE
Don't show the file diff report for first versions of items

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/pre-assembly#1344]
When a first version of an item is created with Preassembly, every file is new. This can create a very long list in the discovery report view of the file differences. Ideally, we would show the file difference only when an item is being updated.

I realize this might be tricky for batches when there's a mix of first versions and later versions. I don't think that's a blocker and I'd need to see what that looks like to determine if it would be a problem.

**Comment by edsu** [comment]
I actually didn't realize that preassembly could create v1 of an object.

**Comment by justinlittman** [comment]
Version 1 is created at registration time. However, pre-assembly contributes to version 1.
