### ISSUE TITLE
Allow resource_label to be blank in file_manifest.csv

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/pre-assembly#1356]
The Cocina model allows the "resource_label" to be blank in structural metadata. This most commonly happens with deposits from H2 but can happen in other ways. Preassembly seems to be requiring data in this field, which prevents using the file_manifest.csv to update items where the existing structural metadata contains a blank.

**To reproduce**

I made a sample item on stage. See this job for the settings:
https://sul-preassembly-stage.stanford.edu/job_runs/16

The file_manifest.csv is exactly what came from the Argo download after I made the initial deposit with H2.

This error appeared in the YML log:
```
:pre_assem_finished: false
:status: error
:message: "[Cocina::Models::FileSet.new] nil (NilClass) has invalid type for :label
  violates constraints (type?(String, nil) failed)"
:pid: sw752vp0288
:container: "/dor/staging/berger-test-accessions/stage/no-labels/sw752vp0288"
:timestamp: '2023-10-09 18:50:25'
```

**Comment by justinlittman** [comment]
closed by https://github.com/sul-dlss/pre-assembly/pull/1360
