### ISSUE TITLE
Upgrade to Rails 7.1

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/pre-assembly#1359]
Following the [Rails upgrade guide](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-7-0-to-rails-7-1), bump pre-assembly from Rails 7.0.x to 7.1.x and troubleshoot test failures and such.

**Comment by ndushay** [comment]
Mike - i wonder if this falls to FR.  I completely get not having it hold up dep updates, tho.

**Comment by mjgiarlo** [comment]
@ndushay up to Vivian, I guess. I could also see this being a decent patch party or unscheduled week activity.

**Comment by ndushay** [comment]
I guess I wonder if we'll be bitten if pre-assembly isn't at Rails 7.1 and most of our other rails apps are.

**Comment by mjgiarlo** [comment]
@justinlittman 🍻
