### ISSUE TITLE
ActiveJob should send Email (depends on #281)

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/pre-assembly#139]
At the completion of the ActiveJob, an email should be sent to the user with details about the job.

Open Question: Will we have the email address for a valid, authenticated user?

**Comment by SaravShah** [comment]
Yes we will - if we know their `sunet_id` we know their email.

**Comment by atz** [comment]
Should probably start by setting up `ActiveMailer` as here:
https://guides.rubyonrails.org/action_mailer_basics.html

**Comment by atz** [comment]
Recommended implementation: in the `JobRun` model, add a callback that sends the email specifically when the object is successfully saved with a new output value.  That means that jobs don't directly need to know anything about email.  

Example (in `JobRun`):
```ruby
after_update :send_notification, if: -> { saved_change_to_output_location? }
...
def send_notification
  JobMailer.with(job_run: self).completion_email.deliver_later
end
```
