### ISSUE TITLE
Add option to configuration menu: "GIS Accessioning"

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/pre-assembly#1397]
The Preassembly "processing configuration" menu enables user to tell the Preassembly app to follow a specific processing logic when accessioning files. Add an option that will enable staging GIS specific data files from globus to the gis-robots-suite (kurma) servers. 

**Describe the solution you'd like**
- Stage files from globus to kurma server(s) at `/gis_workflow_data`
- Initialize gisAssemblyWF

**Comment by andrewjbtw** [comment]
It's possible that entering the content type of "geo" would be sufficient (with a processing configuration of "default") to indicate that gisAssemblyWF is needed, but I'm not sure if any content in another type (map? image?) could also get routed to gisAssemblyWF.

**Comment by aaron-collier** [comment]
https://github.com/sul-dlss/gis-robot-suite/issues/660 Will be required for all environments of kurma-robots when this is deployed.

**Comment by peetucket** [comment]
1. Need a manifest.csv
2. Where do the GIS robots look for content?
3. Does pre-assembly need to generate no structural metadata at all for Geo objects?
4. Need a new staging location for content which is only used for Geo objects: `/gis_workflow_data/stage`
