### ISSUE TITLE
Add language selection and send as workflow context

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/pre-assembly#1439]
We need the language selection option on the pre-assembly batch context form.

See https://docs.google.com/document/d/1ScvlgCI-YhyV2LaaDLTVOWTvuGe4bM1tmgzVbAHTDw8/edit#heading=h.lfkejdmithnz

The selected value will go into the workflow context for the druid version.  If the UI is tricky for the person picking this up, an HTML drop down may be fine as a first pass (and it may be possible to do a multi-select combo box in native HTML dropdown? 🤷  there may also be examples for this in H2 tag UI)

Per the outline document, we may also want to limit or warn that ABBYY wants a max of 8 languages in its ticket.

That value will then go into the ABBYY XML ticket, that is in sul-dlss/common-accessioning#1219

Languages supported by ABBYY: https://help.abbyy.com/en-us/finereaderserver/14/help/langnames/

**Comment by dnoneill** [comment]
https://help.abbyy.com/en-us/finereaderserver/14/help/langnames/

**Comment by alundgard** [comment]
Requesting a small adjustment to the Warning message. Remove "used for auto detection" so that it reads:
`Warning: Selecting more than eight OCR languages may have an adverse effect on the speed and quality of recognition. Please reduce the number of languages.`

**Comment by dnoneill** [comment]
Done

**Comment by alundgard** [comment]
Minor, non-blocking: "Content language" is in sentence case, but "Selected Languages" is in title case. Should be sentence case.
