### ISSUE TITLE
Update pre-assembly form with new text and ordering

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/pre-assembly#1450]
~~Blocked by #1451~~

Will be useful to have #1452 done first.  PR: #1455

OCR options and text have been changed.  This includes the ordering of fields, and make some fields conditional on previous selections.  

We need to make adjustments to text and stimulus controllers to match the new UI.

See https://docs.google.com/document/d/1ScvlgCI-YhyV2LaaDLTVOWTvuGe4bM1tmgzVbAHTDw8/edit#heading=h.lfkejdmithnz

When submitted, the form should still save the same attributes to the `BatchContext` model, so this may require using some helper setter/getters, since some UI elements may not end up being saved (but instead will only trigger elements that will be saved to show).

Note: these changes will require many of the feature specs within the pre-assembly codebase to be updated to deal with the new form values that are being selected.

There will also need to be changes to the integration tests.  This is ticket elsewhere: [sul-dlss/infrastructure-integration-test#734](https://github.com/sul-dlss/infrastructure-integration-test/issues/734)

**Comment by jmartin-sul** [comment]
Decision in planning: this will likely be split into a few tickets, each with more detail.  @alundgard and @peetucket will work on the re-ticketing using mockups and user requirements.
