### ISSUE TITLE
Change "I have a file manifest" to yes/no radio buttons

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/pre-assembly#1464]
Blocked by #1458 --- let's get that big PR done first.

We now have yes/no radio buttons on the pre-assembly form -- this checkbox is better suited as a radio button.

Exact language to be defined.

Also, if the user selects "Media" content type, this must be checked --- add a new validation for this.

**Comment by alundgard** [comment]
"Do you have a file manifest?" [default: No]
<img src="https://github.com/sul-dlss/pre-assembly/assets/2343316/da160394-582e-4fe6-966f-27ca50d9725e" width=600>

**Comment by jmartin-sul** [comment]
@peetucket might just combine this with #1458 

@alundgard says that user testing indicates we should make some slight language changes, but after #1458 gets merged, so we don't keep piling onto that.  may or may not also require integration test changes, depending on what the tests are looking for in the form.  also fine to keep existing language, which is good enough, we just found opportunity for refinement.  @alundgard will ticket shortly.
