### ISSUE TITLE
Set shelve/publish to "yes" for image/jp2 when a user says they are providing OCR

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/pre-assembly#1465]
When a user says they are providing OCR, the [current setting for image/jp2](https://github.com/sul-dlss/pre-assembly/blob/a17f98645bdb62ba6770cc9e8d311295bf320f61/app/lib/pre_assembly/from_staging_location/file.rb#L32C1-L32C73) is

```
'image/jp2' => { preserve: 'yes', shelve: 'no', publish: 'no' },
```

As long as the item is not dark, these settings should be
```
'image/jp2' => { preserve: 'yes', shelve: 'yes', publish: 'yes' },
```

JP2s are different than other image files because `jp2-create` won't run if a JP2 already exists. The expectation is that if you provide a JP2, you want to display that JP2. When the current settings are applied to JP2, you end up with no image files shelved so the viewer doesn't have anything to display.

The `preserve: 'yes'` setting makes sense in this case because the user is providing the JP2s. Unlike auto-generated JP2s that default to `preserve: 'no'`, we should preserve these.

**Comment by peetucket** [comment]
What about `image/jpeg`, should it be changed in the same way or left as is?

see https://github.com/sul-dlss/pre-assembly/blob/main/app/lib/pre_assembly/from_staging_location/file.rb#L29-L38

**Comment by andrewjbtw** [comment]
`image/jpeg` is fine how it is - jp2s will be created for that case. The viewer won't render jpeg anyway, just jp2.
