### ISSUE TITLE
Table overflow in prod

### ISSUE THREAD

**Issue by alundgard** [sul-dlss/pre-assembly#1495]
The tables appear to overflow the screen width in prod, but not on qa.

prod: https://sul-preassembly-prod.stanford.edu/batch_contexts
![Image](https://github.com/sul-dlss/pre-assembly/assets/2343316/2e4d90fc-f974-404f-920d-32db3603f6c4)

qa: https://sul-preassembly-qa.stanford.edu/batch_contexts
![Image](https://github.com/sul-dlss/pre-assembly/assets/2343316/a13c96e8-0e23-4b15-b20f-2f9ef926c191)

**Comment by dnoneill** [comment]
@alundgard They overflow on both qa and prod. I am guessing the table in prod has a couple of columns that are wider than qa. There isn't much we can do except have the overflow be confined to the page (see screenshot). But I don't think there is a way around scroll with such a long table.



![Image](https://github.com/sul-dlss/pre-assembly/assets/19173991/f69d8b39-ad6a-47ca-95d0-ec6c1b5edf95)

**Comment by alundgard** [comment]
Thanks for investigating @dnoneill ! Yes I think you're right: the overflow is due to different data on qa versus prod.

Qa seems to break the longer strings (Name and Staging Location) so that the table fits within the screen. These strings happen to always have a nicely-breaking hyphen char. Prod seems like it doesn't want to break these fields when they don't have a nicely-breaking char.

Would it be weird to apply `word-break: break-all` to the Name and Staging Location columns only? I think that might help with the appearance issue on the Projects History table.

**Comment by dnoneill** [comment]
We can add a word break (bootstrap class text-break) would pretty easy.

**Comment by dnoneill** [comment]
Okay branch with break-all in PR.
