### ISSUE TITLE
Adjust mimetypes for setting transcription roles for speech to text files

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/pre-assembly#1526]
If the user tells us they are providing speech to text files for a media object, do we need to adjust content structure correctly to set the transcription role? 

This would be in `app/lib/pre_assembly/from_staging_location/file.rb` 

or will it be set by the user because for media objects, you must provide a file manifest, which sets those attributes?

Blocked by #1524

**Comment by jmartin-sul** [comment]
we think this is no longer an issue, because we think that structural will be built entirely from the manifest, with no need to consider mime types
