### ISSUE TITLE
need a way for users to get files into and out of ... "directory"

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/pre-assembly#161]
users need to be able to deposit spreadsheets and get (possibly large) reports

- can be via UI upload  OR  can be via write access to directory
- can be via UI download OR can be via access to directory

**Comment by atz** [comment]
I think our perspective on this has evolved in the intervening 14 weeks.

**Comment by ndushay** [comment]
@jmartin-sul Can this be closed in favor of tickets we already have to put output "somewhere" (#78) and make it downloadable via simple view for job run (#295) ... and that documentation for end uses will cover the "input" part.

**Comment by jmartin-sul** [comment]
@ndushay, yup, closing...
