### ISSUE TITLE
Run preassembly job code from console

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/pre-assembly#165]
as a way to see what configs / connections we need, etc.

probably needs at least part of #163

Idea is to get a smoke test running simply (manual check with console) and then write a spec that may just be "run the preassembly code and ensure it doesn't throw an exception and/or outputs "I'm happily completed" message.

So if specific tweaks are needed to get the preassembly code  basically runnable, then a PR should be made for that;

a PR should be made for the end-to-end smoke test spec (can be same PR)

**Comment by jmartin-sul** [comment]
@ndushay  ran into the following:
```
2.4.4 (main):0 Pry > b.run_pre_assembly
2018-09-04 13:58:29 -0700: Pre-assembly started for Revs
2018-09-04 13:58:29 -0700: 3 objects to pre-assemble
2018-09-04 13:58:29 -0700: 3 total objects found, 0 already completed objects skipped
2018-09-04 13:58:29 -0700: 3 remaining in run | 3 running | ~ remaining: 
Working on 'spec/test_data/bundle_input_a/image1.tif' containing 1 files
** [Honeybadger] Unable to send error report: API key is missing. id=6bd43096-552c-418c-a53c-b8a267c8dda9 level=3 pid=1430
ArgumentError: wrong number of arguments (given 0, expected 1)
from /Users/ndushay/sul-dlss-github/pre-assembly/app/lib/pre_assembly/bundle.rb:471:in `validate_files'
```

@atz noticed that it's a namespace collision (should be using `@validate_files` in the guard clause instead of `validate_files`).
