### ISSUE TITLE
migrate config info from cli_environments to settings.yml files

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/pre-assembly#169]
instead of our funky cli_environments directory with .rb files, we should be able to put our settings in to config/settings/xxx.yml files and have an initializer or whatever load them into the appropriate ruby objects.  

Example:  https://github.com/sul-dlss/preservation_catalog/blob/master/config/initializers/dor_workflow_service.rb

**Comment by atz** [comment]
Nice to have, but I don't really see much payoff from this.  We could also just move the `cli_environments` code into initializers and that would be fine.

**Comment by ndushay** [comment]
the payoff is the code is more easily understood by maintainers as it would be in the expected pattern.

**Comment by ndushay** [comment]
I agree that it's not a top priority, but I think it would be useful to get rid of cli_environments

**Comment by ndushay** [comment]
This issue can be closed after:
- [ ] config/cli_environments is removed from shared_configs 
- [ ] config/cli_environments is removed from preassembly code base

**Comment by ndushay** [comment]
yay us!  done!
