### ISSUE TITLE
turn BundleContext into an ActiveRecord model

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#172]
see https://github.com/sul-dlss/pre-assembly/issues/141#issuecomment-417418028

> we'll model the options that a user gave when submitting a job.  to do that we'll just turn `BundleContext` into an ActiveRecord model (have the current class extend `ApplicationRecord`, and make it more ActiveRecord-y):
> * FK back to `User` that submitted the job
> * the various configuration fields will just become ActiveRecord fields
> * we'll switch from the monolithic validation method to individual validations on the model fields
> 
> It would be nice to be able to go to a set of params in history (a `BundleContext` instance), and re-run pre-assembly or discovery report based on that, so that user doesn't have to re-enter params for every run.  @blalbrit says this would be nice to have, but can live w/ users re-entering every time.

**Comment by ndushay** [comment]
done!
