### ISSUE TITLE
define routes more narrowly

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/pre-assembly#179]
Currently, we have ContextBundle routes defined with "resources" but we should only define the routes we intend to use.  

![image](https://user-images.githubusercontent.com/96775/45053168-0dc0cc00-b03e-11e8-93ce-d57a5be3fb29.png)

From 
https://github.com/sul-dlss/pre-assembly/pull/162/files/980057cd33787c0bccc4184092abff9347300df1#diff-21497849d8f00507c9c8dcaf6288b136

**Comment by jmartin-sul** [comment]
routes are now defined more narrowly
