### ISSUE TITLE
investigate shib for user sessions

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#187]
e.g. getting sunet id from apache headers.

see argo, searchworks, etc

**Comment by atz** [comment]
This seems to be a relevant lambda in Argo's devise (specifically `DeviseRemoteUser ` initialization:
https://github.com/sul-dlss/argo/blob/f60a721af7a5007edf1c97ac359cbce39235caf0/config/initializers/devise.rb#L6-L16
