### ISSUE TITLE
use dor-workflow-client gem to talk to workflow-services

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/pre-assembly#194]
See app/lib/pre_assembly/digital_object.initialize_assembly_workflow

**Comment by ndushay** [comment]
See also config/initializers/dor_xxx  and config/settings.yml

**Comment by SaravShah** [comment]
We used `Dor::Item.find` and `dor-workflow-service` doesn't let us do that. We have to use `dor-services` anyways, so might as well keep it as is.

**Comment by ndushay** [comment]
i believe this is done.
