### ISSUE TITLE
assembly/objectfile gem bug (proxy)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/pre-assembly#196]
Note that our smoke test for run_pre_assembly fails without exiftool installed;  unfortunately, the error for this is swallowed and it just appears that a particular image is deemed "invalid"

![image](https://user-images.githubusercontent.com/96775/45067047-1b924380-b076-11e8-86f4-d2721c048dcd.png)

proxy for sul-dlss/assembly-objectfile/issues/11

**Comment by jmartin-sul** [comment]
installed exiftool on the VMs, closing this proxy issue since we're unlikely to get to the assembly-objectfile issue in this work cycle
