### ISSUE TITLE
add a deprecation warning to the legacy branch

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#219]
have it ask the following of the user, if possible for them:
* if unsure whether what they want to do is possible using master branch on new pre-assembly VMs, give it a shot in rails console there.
* once sure it's not possible (either by reasoning from known limitations or experimenting), file a bug noting what desired behavior from the legacy branch needs porting forward to master.
* proceed as before on the legacy branch if needed.

then dev team can use backlog tickets to determine work in a future development cycle.

**Comment by atz** [comment]
I don't understand the intent and audience for this proposed deprecation.  The number of users is small and all are known to us, so if it is just to communicate, we can do that easily w/o code.

**Comment by jmartin-sul** [comment]
when i filed this ticket initially, i thought the audience for legacy (command line) pre-assembly usage was larger than just @blalbrit and @peetucket (for some reason, i had the impression it was 5 to 10 people).  since it appears that ben and peter are the only users of the CL app, i'm fine closing this, since they're already well aware that we're trying to retire the legacy app.

if @atz and i are mistaken, feel free to reopen, @blalbrit or @peetucket.

**Comment by peetucket** [comment]
agreed, i don't think we need a warning

**Comment by blalbrit** [comment]
I agree as well - sadly, it's just me and @peetucket now (_sound of tumbleweeds blowing across the prairie_)
