### ISSUE TITLE
rename BundleContext::YAML_PARAMS to something more accurate (blocked by #172)

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#220]
these are now more like `ALLOWED_CONFIG_PARAMS`, since soon they'll be primarily coming from a web form and some default values, though technically the console would still support use of a .yml file for configuration, and we hope to make that more practical as any needed legacy command-line functionality is forward ported to master (see #219, #221, #62, etc).

**Comment by atz** [comment]
`INIT_PARAMS` is what `DigitalObject` has.

**Comment by atz** [comment]
These are gone in the AR model.
