### ISSUE TITLE
setting for default staging_dir (requires #256)

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#224]
default is '/dor/assembly', currently hardcoded inline in one place in the app and one place in the specs.  would be a good thing to make a setting?

**Comment by ndushay** [comment]
it would be awesome to make any such constants a setting

**Comment by atz** [comment]
BundleContext has:
```
def staging_dir
   '/tmp/assembly'
end
```
Presumably because that makes it work in dev and test.  Not a valid value for production, so this definitely should be a setting.

**Comment by ndushay** [comment]
@atz @SaravShah if we go back to using the assembly-utils gem, we are guaranteed to be using the directory where assemblyWF looks for this data ... what do you think?  Good idea?  Bad idea?

**Comment by ndushay** [comment]
Actually, I can probably clarify just by changing the name to assembly_staging_dir or something like that.

**Comment by atz** [comment]
What are the two things being confused?
