### ISSUE TITLE
get new discovery report service producing working discovery report, from console (depends on #236, blocked by #254)

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#237]
make sure we know the incantations necessary to get things running from the workers.

**Comment by atz** [comment]
Subject says service via console, description says workers.  These are two different things.  I propose you should close this ticket and re-ticket whichever piece of may still be outstanding (but not conflate both).

**Comment by SaravShah** [comment]
okay ill close this

**Comment by jmartin-sul** [comment]
> Subject says service via console, description says workers. These are two different things. I propose you should close this ticket and re-ticket whichever piece of may still be outstanding (but not conflate both).

i think the idea was that we weren't sure what it'd take to get it running from the worker, and that it'd be easier to get things running from the worker if we were able to play around with and debug the invocation from the console first.  could've also just been a bullet point for guidance under #347.
