### ISSUE TITLE
was this TEMPLATE.yml 'use_container' comment change erroneous?

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#243]
the second subdirectory was removed from the structure described in the comments:
https://github.com/sul-dlss/pre-assembly/pull/232/files#diff-2f847418c6070e9dcfbc34cb3fbc0a55L96

spawned by https://github.com/sul-dlss/pre-assembly/pull/232/files#r216766266

**Comment by atz** [comment]
More broadly: does `TEMPLATE.yaml` matter anymore?

**Comment by jmartin-sul** [comment]
see also, #274
