### ISSUE TITLE
discovery report presentation in GUI

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/pre-assembly#257]
~~pre-req issue #258:  discovery report service has been run and persistent artifact is somewhere in JSON~~

~~the templates from issue #236 (or other similar templates) need a GUI presentation for end user to see~~

want a sortable table presentation (probably via javascript);  this is presumaby about the LOG as much as the REPORT.

there could be a transformation from the persistent storage format of the report to some intermediate form which is then fed into the table view, or not.

See also #939

**Comment by jmartin-sul** [comment]
if we have time to do this, astrid says she's fine with us just doing the easy thing, and displaying a simple list of rows with fields.  ben says no need to have the table be sortable or anything.

**Comment by ndushay** [comment]
done enough!
