### ISSUE TITLE
Readme updates

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/pre-assembly#260]
must include, at top, an indication that the v3-legacy branch AND the master branch are deployed in production and need gem updates.  And that deploying to all four cap targets is warranted.

And of course, readme should be changed to reflect the rails app code

**Comment by atz** [comment]
Indeed.  Everything that mentions the old `bin`, `lib` and (especially) `devel` needs to go.

**Comment by jmartin-sul** [comment]
once #335 is merged, we can get rid of the PG section.

do we need exiftool anymore?
