### ISSUE TITLE
remove label and sourceid from plain manifest (not smpl)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/pre-assembly#285]
![image](https://user-images.githubusercontent.com/96775/45566551-d1def100-b80b-11e8-95d8-6017afdca288.png)

**Comment by ndushay** [comment]
@andrewjbtw  says:  

> I’d still like to figure out what’s desirable to port over [from lyberservices-scripts functionality]. I keep learning that Ben uses things from there that no one else knows how to use.
> I could be out of date on the readmes, but at the end of the last maintenance work cycle it looked like the pre-assembly readme still had text about methods not in the UI

**Comment by andrewjbtw** [comment]
This has been done (some time ago).
