### ISSUE TITLE
Shouldn't need postgres in dev or test

### ISSUE THREAD

**Issue by atz** [sul-dlss/pre-assembly#288]
We have a very small number of tables.  We use no postgres-specific technology.  It doesn't make sense to require PG for development or testing.  One of the benefits of using ActiveRecord is that it allows for lightweight development.   We should enjoy that benefit.

**Comment by jmartin-sul** [comment]
yeah, on further thought, PG on laptop is an unnecessary barrier to entry for casual maintenance (e.g. need to install PG just to deal w/ this in patch party if you didn't already have it).

**Comment by jmartin-sul** [comment]
per this thread on #311, we should regenerate schema.rb as part of the PR against this issue, if/when we get to that work:  https://github.com/sul-dlss/pre-assembly/pull/311/files#r218898748
