### ISSUE TITLE
MAINT: test Bundle#discover_containers_via_manifest error conditions

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#291]
the method has guard clauses that `raise` if `manifest_cols` or `manifest_cols[:object_container]` is falsey.  but this is obviously untested, because we accidentally removed the error that was being raised (see #277), and no tests were failing.

#290 returns us to using an error that exists, but tests would be nice.

**Comment by ndushay** [comment]
closing this as the method mentioned doesn't exist any more (or was renamed) and our code coverage data can inform us of missing coverage.
