### ISSUE TITLE
acceptance testing

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#296]
we'll need to get @blalbrit or @peetucket to do some manual testing of all this re-written functionality.

we should also specifically confirm that SMPL bundles run cleanly through pre-assembly and discovery.

**Comment by SaravShah** [comment]
I'm going to do a first pass of this test - just to make sure everythings hooked up correctly. I think @peetucket and @blalbrit will still want to do their manual testing as well.

**Comment by jmartin-sul** [comment]
closing this out, seems to be working in prod, feel free to reopen if need be...
