### ISSUE TITLE
MAINT: tests for error and info collection in DiscoveryReport#process_dobj

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#297]

**Comment by atz** [comment]
Could involve some refactoring of functionality to make smaller more testable methods, e.g.:
- separate method to produce error flags from the base/counts hash.
- separate method(s) for the smpl data/errors to be merged in

Or could just start testing the conditional bits already present.

**Comment by ndushay** [comment]
closing this as our code coverage data can inform us of missing coverage.
