### ISSUE TITLE
Document why repo is private

### ISSUE THREAD

**Issue by atz** [sul-dlss/pre-assembly#3]
Looks like even the sample configs are problematic.  Ideally we move to using shared_configs in production and we should create a public version of this repo that is clean.  Until then we should document (here, in README, wherever) what the holdups are.  

This is important because if future changes remove those reasons from the filesystem, the motivating reasons are **still** there in git history.  A diligent but naive developer could determine "no sensitive data in the project" without an awareness of project history and mistakenly move the repo public.

**Comment by peetucket** [comment]
repo is no longer private
