### ISSUE TITLE
route that shows log file mentioned in job completion email

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#300]
just a thin controller that presents the log file we output from pre-assembly.

can see this as a "view" of the `JobRun` model.  could force download if it's too big or something, maybe just always force download for implementation simplicity.  need fallback for no output location in case where user is going view a job that's unstarted/unfinished.

but from rails POV, prob easiest to implement by thinking of this as a view on the job run.

**Comment by atz** [comment]
This implementation should probably be paired with (and is probably easiest to understand as part of) building at least the skeleton of a `JobRunController`

**Comment by jmartin-sul** [comment]
dupe of #295

**Comment by jmartin-sul** [comment]
reopening since @atz already has work against this.  note that there is scope overlap with #295.  at the time of this comment, @jermnelson has picked that ticket up, but has held off on starting it so far.
