### ISSUE TITLE
is discovery report empty_object logic backwards?

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#306]
this seemed odd to me:
https://github.com/sul-dlss/pre-assembly/blob/master/app/services/discovery_report.rb#L55
```ruby
errors[:empty_object] = true if counts[:total_size] > 0
```

maybe i'm wrong, but wanted to capture that for investigation so it doesn't get lost.

noticed while reviewing a PR that didn't actually touch that line: https://github.com/sul-dlss/pre-assembly/pull/276#discussion_r218264402

**Comment by atz** [comment]
Yeah, probably should be `unless`
