### ISSUE TITLE
where/when should BatchContext check for existence of the output location?

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#307]
currently, this is happening via ActiveRecord validations.  but the intent for usage of such validations is just to validate information on the model that's intended for storage in the database.  validation based on state outside the database is something of a mis-use of AR validations.

we can live with this for now, and we might not get to fixing this up in the current work cycle, but wanted to at least capture the intent to move away from the current approach.

**Comment by atz** [comment]
This has been moved to a `before_save` callback (so not strictly a model validation anymore).

**Comment by andrewjbtw** [comment]
Is this still relevant/desired?

**Comment by ndushay** [comment]
I'm closing this ticket;  if it's important, it will surface again.  I think it's not important as it's been hanging out for almost 4 years.
