### ISSUE TITLE
BatchContext: can #verify_output_dir be split into two more readable callbacks?

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#316]
@atz suggests splitting the current verification method to a method for each of the cases it checks (initial creation, where the directory is expected not to exist, and save upon update, where the directory is expected to exist already):  https://github.com/sul-dlss/pre-assembly/pull/311/commits/db327774b8092f907ca3d19b83ea3e95b0621855#r218911606

the thinking is that this will make the functionality clearer and more readable.

**Comment by ndushay** [comment]
method (as named) no longer exists
