### ISSUE TITLE
bundle_context.rb:  move `require 'fileutils'` to a more central location

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#317]
per @atz in https://github.com/sul-dlss/pre-assembly/pull/311/commits/db327774b8092f907ca3d19b83ea3e95b0621855#r218909091 :

> This is unnecessary to use `FileUtils` here.  Compare to `DigitalObject`.
> 
> Because of the way rails auto-loading works, if it were required, it is more typical to put the `require` in a "central" location, so all the app has access to it.

**Comment by atz** [comment]
Subject is mistaken.  The point is that the require is not necessary there or anywhere new, as evidenced by the fact that `DigitalObject` already uses the same gem just fine (w/o any equivalent `require`).  

Fire up `rails console` and try it yourself:
```ruby
> FileUtils.mkdir_p('tmp/foo')
 => ["tmp/foo"]
```
No exception and the directory is created.  So, how could you be in *any* part of the initialized application and **not** have access to that code?
