### ISSUE TITLE
email usability enhancements

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#318]
- [x] it would be great if emails sent had project name in subject
- [ ] discovery report email subject should indicate number of objects and error count (or at least whether or not there were errors)
- [ ] it would be great if preassembly job email subject had number of successful and number of failed objects in subject

feel free to break into smaller tickets if its easier to just implement one part at a time.

**Comment by atz** [comment]
Box 1 checked by #368

**Comment by jmartin-sul** [comment]
fine to just put table contents in email for discovery report

**Comment by peetucket** [comment]
Closed in favor of #976
