### ISSUE TITLE
fake shib info in dev environment

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#323]
can do something like what argo does, except that we only care about the `REMOTE_USER` part (`eduPersonEntitlement` is about workgroups, but pre-assembly app itself doesn't care about specific workgroups since there's no permissions granularity, and access gating by workgroup happens before the request even reaches the app).

see:

https://github.com/sul-dlss/argo/blob/f60a721af7a5007edf1c97ac359cbce39235caf0/lib/test_shibboleth_headers.rb#L11-L15

https://github.com/sul-dlss/argo/blob/f60a721af7a5007edf1c97ac359cbce39235caf0/config/environments/test.rb#L52-L53

in the meantime, a developer can do this manually on the command line by starting their rails server as follows:
```sh
REMOTE_USER=user@stanford.edu bundle exec rails server
```

this works because webauth passes the user info via env vars, as seen in the referenced argo code.

the actual email address specified for `REMOTE_USER` doesn't really matter, unless the developer is attempting to test something that depends on a particular user ID.

alternatively, we could just add the info about manually providing `REMOTE_USER` to the readme, but faking a default user is probably easier for spinning up new developers.

**Comment by atz** [comment]
The two things are orthogonal: whatever is done in test headers doesn't affect spinning up the server in dev.  I think the `REMOTE_USER` env var approach is clunky, but sufficient for now.

**Comment by atz** [comment]
I think we can close this?

**Comment by SaravShah** [comment]
yeah this seems closeable.

**Comment by jmartin-sul** [comment]
at the very least, i think we should put some guidance in the README, even if we don't do the automatic user setting that argo does.  i don't think we should leave a new dev to have to browse the code and figure out what's going on when they try to `bundle exec rails s` and every page gives a cryptic `This application requires a Shibboleth Authenticated user.`.
