### ISSUE TITLE
JobRun history view

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#330]
create `index` controller, templates, etc for `JobRun`s, to display the list of jobs that have been run (we already have WIP for the detail view for a single `JobRun`).

**Comment by atz** [comment]
Since the design right now only has this history displayed in an overlay on the BundleContext page, it makes sense for the first implementation of `JobRunController#index` to target JSON as the output, since the user will not be directly on a `JobRunController` HTML page.
