### ISSUE TITLE
was smpl_manifest.csv different functionally from manifest.csv?

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#336]
@blalbrit ?

**Comment by atz** [comment]
Yes, it  operates at a different level of representation.  File vs DigitalObject (druid).

**Comment by jmartin-sul** [comment]
if they select a project that is smpl, they have to provide a smpl_manfiest.csv (because the code will look for that file).

describes things at the file level (which files go with which objects in the bundle).
