### ISSUE TITLE
what other okcomputer checks do we need?

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#339]
stub initial implementation indicates:
```ruby
# by default, okcomputer does "app up?" and "database conntected?" checks
```

see #334

other possibilities:
* can connect to fedora?
* can connect to WFS?
* can read from... ?
* can write to... ?
  * adequate space in... ?

**Comment by atz** [comment]
Not feeling fedora/WFS checks.   As infrequently as this app is actively used, those alerts aren't going to as be meaningful as just getting the honeybadger exceptions.

**Comment by jmartin-sul** [comment]
fair point.  easy enough to reopen this and add more checks if needed.  closing this one.

**Comment by jmartin-sul** [comment]
ok, actually, @atz says maybe add a redis check, because it's cheap (box on the same machine, canned check available or at least pattern from pres cat, so cheap both in terms of resource usage and dev time).

reopening and putting in backlog.

**Comment by jmartin-sul** [comment]
@atz also points out that we can make some checks optional, if we want the status info, but don't want to give pager alerts for them (e.g. connection to fedora at 5 am when no one's using the app)
