### ISSUE TITLE
resque lock: make it so that only one thing happens with a bundle context at a time

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#352]
keep pre-assembly from stepping on itself and discovery report, since both use progress log.  fine for pre-assembly or discovery report to pick up from a partial progress log, but only one thing should be reading from or writing to it at any given time.

**Comment by atz** [comment]
To be clear, discovery_report consumes (is affected by) the presence of a progress log, but does not produce it.  It reads it in an instantaneous way (parsed once).  The concern is that during a long-running preassembly, a long-running discovery_report might be started, but by the time it is done, the output is about a state that doesn't really exist anymore.  

Also may be problematic to have the same report produce no output after preassembly is run (though this is apparently what users have been getting till now).

**Comment by jmartin-sul** [comment]
closing this.  we'll just document the expected behavior (i.e., discovery report will run on the objects that remain according to the progress log at the time discovery report starts, even if progress log changes while discovery report is running).
