### ISSUE TITLE
Default to discovery report on form

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/pre-assembly#382]
The initial form in the app currently defaults to Pre Assembly Run. Can we default, instead, to the Discovery Report? Most users will begin with that step, and often repeat it, and I would like to reinforce the behavior of not skipping it - making it the default seems like an easy way to do that.

That is here (Pre Assembly Run s/b Discovery Report):
![screenshot 2018-10-01 12 36 16](https://user-images.githubusercontent.com/796990/46311433-01655b80-c577-11e8-92c7-cc6b6f7af817.png)

**Comment by jmartin-sul** [comment]
@atz points out that this could be done by specifying a default enum value, similar to what he did in other classes with enums
