### ISSUE TITLE
restrict allowable paths for bundle input dir

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#387]
we should restrict to the mount paths on the pre-assembly box.

@blalbrit can provide a whitelist of valid input paths.

**Comment by jmartin-sul** [comment]
this is something of a security issue.  we also want to make sure they don't do sneaky things like going from a whitelisted root path but then backing up using relative dirs via `..` etc.

**Comment by jmartin-sul** [comment]
for tests, the rspec spinup can add the fixture paths to the whitelist.  then, don't have to do anything env dependent in regular app code.

**Comment by blalbrit** [comment]
The active mounts are listed at https://consul.stanford.edu/display/CollAcc/Content+Mount+Paths (mount path column for the path that is accessed from the preassembly box)
