### ISSUE TITLE
(uber ticket) Add option for "re-accession"

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/pre-assembly#423]
Users frequently wish to completely overwrite already-accessioned content. At the moment, that is possible, but produces a versionMismatch error in the accessionWF.

This option should appropriately handle addition of a versionMetadata stanza.

At the moment, we are manually adding a new stanza to versionMetadata (not using the versioningWF), which appropriately updates the versionMetadata datastream for the accessionWF. The reaccession job should handle this automatically.

See also sul-dlss/argo#1147

**Comment by ndushay** [comment]
I *think* we want to enable this three separate ways (right @blalbrit @andrewjbtw @hannahfrost?):

- single object in Argo (sul-dlss/argo#1147)
- bulk async action in Argo (sul-dlss/argo#1147)
- via pre-assembly (this ticket)

Ben says:
> Main thing is to make sure that it is possible to use the pre-assembly tool to completely overwrite an object without creating a version-mismatch error.

**Comment by ndushay** [comment]
@jcoyne says:

> One reason this is happening is because pre-assembly does not check to see if there is already an existing version in an accessioned state. If there was, then pre-assembly should call Dor::Services::Client.object(@object.pid).open_new_version(vers_md_upd_info: vers_md_upd_info). This becomes important now because the new workflow service keeps track of which version is active. With the old workflow service, just updating the version stanza in the versionMetadata datastream was sufficient.

**Comment by ndushay** [comment]
I believe this ticket will be addressed when sul-dlss/pre-assembly#525 is done.

**Comment by ndushay** [comment]
I'm closing this ticket;  please re-open if I am in error.  I believe we have implemented a way to reaccession with preassembly.
