### ISSUE TITLE
bundle objects so that .obj file gets resource type = 3d and mime type = plain/text

### ISSUE THREAD

**Issue by snydman** [sul-dlss/pre-assembly#428]
per https://jirasul.stanford.edu/jira/browse/DEVQUEUE-229

Pre-assembly needs to bundle objects so that .obj file gets resource type = 3d and mime type = plain/text (or text/plain as the UV seems to prefer - see below)

@blalbrit has provided a few models for further analysis:
1) https://dms-data.stanford.edu/data/manifests/v3test/sj957jc8666/manifest1.json - strips out all non-3d resources, works in UV currently
2) https://dms-data.stanford.edu/data/manifests/v3test/sj957jc8666/manifest2.json - all resources present, does not work in UV currently

For comparison, what is currently being produced by our manifest creator: https://purl.stanford.edu/sj957jc8666/iiif3/manifest

**Comment by aaron-collier** [comment]
Broken example: https://purl.stanford.edu/bg387kw8222 and manifest: https://purl.stanford.edu/bg387kw8222/iiif3/manifest?manifest=https://purl.stanford.edu/bg387kw8222/iiif3/manifest

Notice file object types and formats need to be updated. This is probably the first priority ticket (fro infrastructure) to move forward. Any clarification @blalbrit ?

**Comment by peetucket** [comment]
Should be fixed by upgrading the `assembly-objectfile` gem once this PR is merged a new gem release is cut: https://github.com/sul-dlss/assembly-objectfile/pull/7
