### ISSUE TITLE
Use dor-services-client

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/pre-assembly#430]
https://github.com/sul-dlss/pre-assembly/blob/bbd5794601900b7a548ad25b2b0044d78cfeacc2/app/lib/pre_assembly/digital_object.rb#L267

Also:

https://github.com/sul-dlss/pre-assembly/blob/v3-legacy/lib/pre_assembly/digital_object.rb#L501

**Comment by mjgiarlo** [comment]
This is done in `master` but still needs doing in the `v3-legacy` branch. That is up next for me. Re-opening.

**Comment by jcoyne** [comment]
@mjgiarlo what is the `v3-legacy` branch for?

**Comment by mjgiarlo** [comment]
Hey, folks who recently worked on pre-assembly (@atz @ndushay @SaravShah @jmartin-sul), I have a question for you: the GH project description and README both mention the `v3-legacy` branch. The former asserts that we ought to continue maintaining the deploying this branch. The latter suggests it ought to be considered deprecated. Can y'all clarify this? Thanks!


cc: @jcoyne

**Comment by mjgiarlo** [comment]
@jcoyne From a Slack thread:

> ...the v3-legacy branch allows for a CLI that the new master branch does not implement. as well as some additional functionality that we may want in the future? 
> 
> v3-legacy deploys to: `sul-lyberservices-prod.stanford.edu`

**Comment by mjgiarlo** [comment]
Absent some plan or timeline to discontinue using the stuff in `v3-legacy`, my preference is to port the work in https://github.com/sul-dlss/pre-assembly/pull/432 to `v3-legacy`.
