### ISSUE TITLE
Support for content structure "Document"

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/pre-assembly#444]
Goal: add "document" to the list of available content structures in pre-assembly app.

The "Document" content type supports the following assumptions at the moment:
* 1 resource containing a file of type PDF, with publish/shelve/preserve settings = yes
* resource type = "document"
* contentMetadata type = "document"
* stubbed contentMD for this type should be as above, with a full sample included at the end of this ticket.

As an example: objects currently in Argo at https://argo.stanford.edu/catalog?f%5Bcontent_type_ssim%5D%5B%5D=document&page=1

Preliminary description in Consul: "for content-type=document, resource types are:
document – must contain a file that is supported for viewing, starting with PDF (any requirements, limitations?).  Other types may be added in the future. 
alternative model: distinguish resource-type to correspond with different types of docs."

Documentation of this model needs to be updated in Consul to reflect current in-production status and provide a full sample of the model.

Sample contentMD:

```
<?xml version="1.0"?>
<contentMetadata objectId="bc934nk0577" type="document">
  <resource id="bc934nk0577_1" sequence="1" type="document">
    <label>Object 1</label>
    <file id="AnnRepIN1907.pdf" mimetype="application/pdf" size="11860369" preserve="yes" publish="yes" shelve="yes">
      <checksum type="md5">e0f804033c15a77fa4c25401b8686986</checksum>
      <checksum type="sha1">e2ef811da024740d3932779d4d28aa40f6e06216</checksum>
    </file>
  </resource>
</contentMetadata>
```

**Comment by andrewjbtw** [comment]
Covered in https://github.com/sul-dlss/pre-assembly/issues/665
