### ISSUE TITLE
EPIC: Support for content structure "Book with OCR"

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/pre-assembly#450]
Page-level OCR .xml or .txt files should be published and shelved, with `role="transcription"` attribute applied to those files.

**Comment by andrewjbtw** [comment]
This is possible with the file manifest but hasn't been turned into its own content profile:
https://github.com/sul-dlss/pre-assembly/wiki/Accessioning-complex-content

**Comment by ndushay** [comment]
This epic has been completed.  I'm closing it.  If that's a mistake, please re-open and add to the board.
