### ISSUE TITLE
colors of buttons on job page are confusing

### ISSUE THREAD

**Issue by hannahfrost** [sul-dlss/pre-assembly#492]
New users find the colors of the buttons labeled "Discovery Report" (green) and "Run pre-assembly" (red) to be confusing. Also the "Details" button is red. 

Red implies "stop", especially juxtaposed with the button colored green (which implies "go")

Can we change the buttons to colors that are less loaded with meaning?

**Comment by astridu** [comment]
@andrewjbtw Is this something we can sneak in to an upcoming work cycle? Can we just change all the button colors to blue #00548F?

**Comment by andrewjbtw** [comment]
Sounds good to me.

**Comment by andrewjbtw** [comment]
Discussed this today with @astridu - the blue was originally for consistency with Argo but Argo no longer has blue buttons. So instead of blue, we should make the buttons red. I think that just means making the one green button red - all others are already red.

**Comment by ndushay** [comment]
I can make them all read, no problem.
