### ISSUE TITLE
Add registration to pre-assembly app

### ISSUE THREAD

**Issue by Mellen22** [sul-dlss/pre-assembly#493]
**Is your feature request related to a problem? Please describe.**
I am frustrated that registration through the argo interface can only be done with batches of objects of about 500. Some of our collections have thousands of objects, and it is time consuming to make batches, and use a slow web GUI to add the objects. This is a factor for EVIS, University Archives, and Laura Wilsey/Sally DeBauche in SPEC/Manuscripts. See https://jirasul.stanford.edu/jira/browse/ARGO-502

**Describe the solution you'd like**
Add registration as a feature to the pre-assembly app. This would eliminate the use of the slow graphical interface that exists in argo. In addition, this improvement would allow entire batches to be registered at once. And additional work time would be saved because there would be a smooth transition between registration and accessioning. Instead, now, we must extract the registration information from argo, create, format, and upload a spreadsheet to another server, potentially introducing additional human error.

**Describe alternatives you've considered**
We currently use argo for registration. I'm not aware of other options currently available. 

**Additional context**
Here is the original ticket: https://jirasul.stanford.edu/jira/browse/ARGO-502

**Comment by ndushay** [comment]
See also https://github.com/sul-dlss/argo/issues/1396

**Comment by ndushay** [comment]
@blalbrit @andrewjbtw @hannahfrost would this ALWAYS be desireable, or would we need some sort of flag to know "yes do it" vs "no don't do it"?

Also, doesn't pre-assembly expose problems with objects?  How would we deal with a set of objects that don't all pass muster?

**Comment by blalbrit** [comment]
I'm not sure this is desirable at all. Bulk registration via Argo (and eventual integration of pre-assembly into a single UI with Argo) seems more logical than having multiple paths to registration in different related DOR apps.

However, I'll defer to @hannahfrost and @andrewjbtw if they feel strongly.

**Comment by Mellen22** [comment]
Currently the pre-assembly app is a two step process (with two buttons). 
1. Discovery report (checking for errors before pre-assembly)
2. Pre-assembly
Registration could be another step that goes before discovery. Or perhaps there needs to be yet another step before that.
1. Check before registration
2. Registration
3. Check before pre-assembly (discovery report)
4. Pre-assembly

What would bulk registration in Argo look like? Currently we paste columnar data into a web form. Would there be a different way to do it in Argo that would mean less time waiting for a web form? or an easier way to transition between registration and pre-assembly? If so, we should discuss. As of yet, having registration be part of the preassembly app seems like it would be most likely to result in decreased errors and improved throughput.

**Comment by ndushay** [comment]
Note:  this is linked to #sul-dlss/argo/issues/1396, which is likely to be the approach taken to resolve this.

**Comment by ndushay** [comment]
Thanks @Mellen22.  Your last comment was super helpful.

**Comment by ndushay** [comment]
clearly a group f2f discussion is needed to determine the best path forward to achieve this goal.

**Comment by hannahfrost** [comment]
I think there are both technical and UX issues -- both short term and long term -- to consider when figuring out where best to add a beefy registration feature. @astridu has almost certainly been thinking about this too!

**Comment by andrewjbtw** [comment]
We have bulk registration now, which covers the main need here. There remain architectural and UX questions about the relationship between registration and preassembly. I'm closing this because we haven't decided whether to:

- add registration to preassembly
- add deposit ability to Argo
- something else where deposit and registration would be combined
