### ISSUE TITLE
Adjust the content preparation script (used by maps accessioning) to search all sub-directories

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/pre-assembly#504]
The current content preparation script used by the maps accessioning team currently only searches in a given directory and does not search the sub-directories.  They would like it to search all sub-directories as well.

The script is in v3-legacy branch.

see https://consul.stanford.edu/pages/viewpage.action?pageId=146704638 for documentation and background

**Comment by ndushay** [comment]
merged PR, so now pls deploy somewhere and have user approve, then deploy to prod (if not done already) and then close this ticket.
