### ISSUE TITLE
Resque-web should not be open to the world.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/pre-assembly#511]
Currently anyone can go to https://sul-preassembly-prod.stanford.edu/resque/workers which allows them to delete queues, etc. Should this have a list of authorized users?

**Comment by jmartin-sul** [comment]
fwiw, i believe it's all behind webauth, so only people in groups with permission to visit the pre-assembly app will be able to get to that admin page.  e.g., if i visit that URL in a browser without a webauth session, i get redirected to the login page, and if i visit from my phone, i get a timeout.

i could imagine restricting that access to e.g. argo super users, though.

**Comment by vivnwong** [comment]
The process is documented here https://github.com/sul-dlss/pre-assembly/wiki/Discovery-Report-and-Accessioning. If we change the access rights, need to update documentation and publish the change to the user group.

**Comment by blalbrit** [comment]
At the moment, I would defer to @andrewjbtw about restricting access. It has been helpful in the past to keep that open to all approved pre-assembly users (who are, by definition, privileged users who have broad access permissions). It is particularly helpful for users like @oceanofsound  and others to check what might be going wrong with one of their jobs. Unless we significantly improved error reporting in the app, I would argue for keeping it open to all pre-assembly users for now.

Also - is this behavior different for https://sul-lyberservices-prod.stanford.edu/robots/overview - which seems equally open and has not caused concern in the past? Open to a broader list of participants as well?

**Comment by jmartin-sul** [comment]
i think @blalbrit makes good points.  i would be inclined to close this issue in light of that reasoning, but i don't have strong feelings myself.

**Comment by andrewjbtw** [comment]
I am inclined to agree with @blalbrit at this point and keep the permissions as is for now. As I get more up to speed on how all of the systems connect, I do want to understand better who monitors that page and what they do with that information (ping slack, contact the repo manager, wait patiently, etc.). As Ben says, if we were to close access, we'd need to provide that information in another way.

**Comment by jcoyne** [comment]
Okay, I see we are doing:
```
    Require shib-attr eduPersonEntitlement sdr:accessioning
```
in the httpd conf, so it's restricted appropriately.
