### ISSUE TITLE
Change references to "smpl" content type to refer to media instead

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/pre-assembly#515]
**Is your feature request related to a problem? Please describe.**

With the change to using "Media" instead of "SMPL" in the Content structure dropdown, we should change other references to "smpl" to use "media."

**Describe the solution you'd like**

Currently, the manifest for this option must be called "smpl_manifest.csv". It should have a more generic name, such as "media_manifest.csv".

Also, the content metadata creation style is referred to as "smpl_cm_style" in the details view for a pre-assembly job. This also should have a more generic name, like "media_cm_style".

![smpl_cm_style](https://user-images.githubusercontent.com/8975583/62891212-013afe00-bcfa-11e9-8f17-a4457e9b8484.png)

**Describe alternatives you've considered**
Things could be kept as they are, but there would be a mismatch between the "Media" label and the other references.

**Additional context**
This option started out as a SMPL specific use case but more users have a need to accession media than just SMPL. We will need to notify existing users of the change in manifest file name.

**Comment by ndushay** [comment]
This has been coded, deployed to stage, vetted by Andrew and merged to master.  We expect it will be deployed on Monday, Aug 19 with the dependency update deployments.  Closing the ticket.
