### ISSUE TITLE
Rescue exceptions on a digital object and allow the job to continue

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/pre-assembly#532]
The bundle context is the wrapper for a complete pre-assembly job.  This wrapper class calls the digital_object class for each object to be accessioned.  If  any one digital object has a problem and throws an exception, the whole job will stop and never complete, throwing it in the failed queue in Resque.  It would be nice if we could allow the job to continue so the rest of the objects can process, and simply place the exception for the object(s) in error in the output log file.

Or we should minimally throw the job into an error state this is visible in the pre-assembly UI, so a job does not get stuck in "Incomplete" forever in the pre-assembly app.

pre-req: #535

**Comment by ndushay** [comment]
@jcoyne - if you're working on this ticket, would you mind assigning it to yourself?  Thanks.

**Comment by peetucket** [comment]
This is part of what I am doing on #535.  Will assign to myself
