### ISSUE TITLE
Media content metadata generation failing

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/pre-assembly#534]
See https://app.honeybadger.io/projects/52900/faults/53704633

When the user selects "Media" in the "Content metadata creation" drop-down menu when creating a job, this should set the style to "media_cm_style" and the code appears to do this correctly.  This should then trigger the media specific content metadata generation call from `digital_object#create_content_metadata` instead of passing that style to the Assembly::ObjectFile gem, but it doesn't appear to be doing that anymore according to the HB alert.

**Comment by ndushay** [comment]
@peetucket if this turns out to be a non-issue after conversing with Geoff, please close it.

**Comment by peetucket** [comment]
Will close for now -- he said all is fine.
