### ISSUE TITLE
Create a new state of job runs that shows completed jobs that had errors

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/pre-assembly#535]
Goes along with #532 and PR #533.  Before we allow a single object to be logged and the job to continue, we need a way to let the user know that although their job completed, there was at least one object that an error.  This will encourage them to examine the job detail log to see what happened and which object needs to be worked on.

So instead of just having a job run end in either "running" or "done", we need a "done with errors" that can be triggered if at least one digital object failed to process.  Currently we just infer the state of "running" vs "done" by the presence of the output .yml log file.  So this would require adding a new "state" column to the job run table and do a better job of tracking that way.

**Comment by ndushay** [comment]
@peetucket if you're working on this, would you mind assigning the ticket to yourself?  If you're not working on it, would you mind putting it back where you found it?

**Comment by peetucket** [comment]
Yup, oversight.  Dragged to in progress but didn't self assign.  Did that now.
