### ISSUE TITLE
Add a link to the resque queues from the job runs page

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/pre-assembly#536]
It is very helpful when a job never completes to look at the queue and see what the error actually was.  The link to resque is currently embedded in the Usage Instructions wiki in a troubleshooting section -- thought it would be useful to surface it directly in the app for speedier debugging.

**Comment by ndushay** [comment]
I'm gonna close this as it's not some big user facing thing that needs vetting, IMO.
