### ISSUE TITLE
Way to add new content structure (e.g. 3d, document, cats)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/pre-assembly#546]
from #221, there is a desire to be able to add new content structure easily (e.g. 3d objects #427, document #444, book with OCR #450)

At a minimum, "how to" documentation could be helpful.

originally worded in #221 as:

>update list of content structure easily (that is, develop a pattern for adding new models like is being requested in #427 )

**Comment by andrewjbtw** [comment]
This is possible with the file manifest now for all content types. Some cocina-related updates are in the works, and more documentation is needed, but there is a document here that explains the complex use cases: https://github.com/sul-dlss/pre-assembly/wiki/Accessioning-complex-content
