### ISSUE TITLE
support for very large projects (on the order of > 100K)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/pre-assembly#547]
from #221:

> possibly beef up worker support for very large projects (on the order of > 100K objects in a pre-assembly run)

**Comment by andrewjbtw** [comment]
I'm closing this because preassembly has successfully accessioned batches up to 30k and very likely could handle larger batches if we had them. If we find an upper bound, then we can open a new issue with specific information as to why that project size was too large.
