### ISSUE TITLE
expose pre-assembly and discovery report functionality via web UI (blocked by...)

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#62]
current plan:  rails-ify the pre-assembly codebase.

this ticket will likely spawn many other specific implementation tickets.  we can use this ticket as a catch-all to track the whole set of work around this.

**Comment by jmartin-sul** [comment]
see
#119
#84

**Comment by atz** [comment]
This is basically done (as far as coding).

**Comment by jmartin-sul** [comment]
i'm going to close this in favor of #296 (UAT) and the more granular implementation tickets we have.
