### ISSUE TITLE
Add option to set all files to preserve="yes" shelve="yes" publish="yes"

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/pre-assembly#625]
A common use case for the command-line lybserservices-scripts accession method is to set all files in an accessioning batch to `preserve="yes" shelve="yes" publish="yes"` in the contentMetadata. 

This ticket is to provide a way for users to set those options to yes for all files in all items in a preassembly job. This will lessen the need for the repository manager to accession items on users' behalf, as they will be able to use preassembly for these use cases.

This is an especially common request for research data deposits that are too large to go through Hydrus self-deposit. Hydrus itself sets these attributes to yes when using the self-deposit form.

**Note on current behavior**

Currently (to my knowledge), pre-assembly sets those attributes based on 

- mime-types, set via assembly-objectfile
- the media manifest, used with the media content type

**Comment by vivnwong** [comment]
@astridu can you provide a UI design for this feature in the pre-assembly app?

**Comment by ndushay** [comment]
@andrewjbtw - I assume the converse is not needed -- to set everything to no??

**Comment by andrewjbtw** [comment]
Correct. All the other combinations will be a mix of yes and no, which makes it harder to set with a simple flag.

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/76982893-c46f5f00-68f9-11ea-950f-2bdd837fa63f.png)
Add a new dropdown to the form. 
Dropdown label: Preserve, Shelve, Publish Settings
Dropdown values: 
- Default (this is selected by default)
- Preserve=Yes, Shelve=Yes, Publish=Yes

**Comment by jcoyne** [comment]
@astridu  I'm not sure the text under the drop down makes sense for "default" because it is not constant across every file. It varies by file mime-type.
<img width="552" alt="Screen Shot 2020-03-18 at 11 27 33 AM" src="https://user-images.githubusercontent.com/92044/76983471-77948400-690b-11ea-93d6-8a68dcf3b25e.png">

**Comment by astridu** [comment]
That's why we called it 'Default' because it varies by file. That's one option is to select whatever the default is, and then the other option is to set all to Yes.

**Comment by astridu** [comment]
It will look like this to the user. 
![image](https://user-images.githubusercontent.com/42216982/76983888-57f55f80-68fb-11ea-909c-0f51215a8ee9.png)

**Comment by astridu** [comment]
And if they select the dropdown, then they see the Preserve/Shelve/Publish = Yes

**Comment by jcoyne** [comment]
@astridu is that a bit redundant if the select option is "Preserve=Yes, Shelve=Yes, Publish=Yes"?

**Comment by astridu** [comment]
I don't think there are any default options that is also Preserve/Shelve/Publish = yes? I don't understand what is redundant.

**Comment by jcoyne** [comment]
@astridu earlier you said:
> Dropdown values:
>
>   Default (this is selected by default)
>   Preserve=Yes, Shelve=Yes, Publish=Yes

We don't need to show help text below the dropdown "Preserve/Shelve/Publish = yes" if the option in the dropdown box is "Preserve=Yes, Shelve=Yes, Publish=Yes" right?

**Comment by astridu** [comment]
No tooltip/help text necessary. Users who select that option know what it is. Thank you!

**Comment by jcoyne** [comment]
@astridu since this is just an either/or, would it be better to use checkbox? Then the users can see the option without having to manipulate the widget (if they want the default)

**Comment by astridu** [comment]
That works too. 
![image](https://user-images.githubusercontent.com/42216982/77010479-17abd680-6927-11ea-9824-1a5918bcf8ed.png)

**Comment by andrewjbtw** [comment]
That works for me too. I just want to make sure that if someone doesn't think about the setting at all they end up with the defaults.
