### ISSUE TITLE
add okcomputer feature check for 5 workers 

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/pre-assembly#628]
**Is your feature request related to a problem? Please describe.**

Nagios alerts when the worker count isn't exactly 5.

**Describe the solution you'd like**

We should have an okcomputer check for ensuring there are *at least 5 workers*.  preservation-catalog has one:

![image](https://user-images.githubusercontent.com/96775/76778329-de2c6d00-6766-11ea-820f-cb4cec41a198.png)

**Comment by julianmorley** [comment]
See https://github.com/sul-dlss/preservation_catalog/blob/master/config/initializers/okcomputer.rb#L82-L94 for an example from prescat (h/t @jmartin-sul ). I'd suggest expanding this into a case statement that differentiates between count high and count low conditions.
