### ISSUE TITLE
post some sample content on which to run preassembly and discovery report on stage

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#63]
to allow devs to do some testing and iteration on the pre-assembly codebase while exposing functionality via web UI (#62).

something that's small enough to get processed reasonably quickly, so we can run repeatedly.

**Comment by blalbrit** [comment]
Two batches of sample content that can be used for testing:

1. /dor/staging/burke2/content (paired with /dor/staging/burke2/burke2.yaml for configs)
2. /se1/SPEC (paired with /se1/spec.yaml)

Item 1 is a small amount of content, item 2 is a larger set. Let me know if you need additional stuff - we can revisit when the code is deployed to build out a larger set of test content if necessary.

**Comment by blalbrit** [comment]
Third project added for testing:

3. /dor/staging/M2297/tag_test.yaml

This tests a mixed set of content (registered as either image or file) to see if the content_tag_override configuration works. Can be used as a general test as well.
