### ISSUE TITLE
Do not publish or shelve dark content

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/pre-assembly#638]
**Describe the bug**
Content accessioned via pre-assembly is being shelved when the rights are set to dark. For dark content, no files should be shelved or published. They should be preserved only.

For example, see the items with the Project tag of EVIS:
https://argo.stanford.edu/catalog?f%5Bproject_tag_ssim%5D%5B%5D=EVIS

All of these materials have rights set to dark and are accessioned via pre-assembly. Instead of setting the files to preserve-only, they are getting the default publish and shelve permissions set by pre-assembly. You can find the files for these items on Stacks.

**To Reproduce**
1. Go to Pre-Assembly
2. Accession content whose rights are set to dark
3. See that files will get default publish/shelve settings, rather than publish=no, shelve=no

**Expected behavior**
A rights setting of dark overrides all other settings. Content accessioned dark should not get published or shelved.

**Additional context**
The rights setting is preventing the purl from being published, so that the files are not accessible even though they are being sent to Stacks. This mitigates the issue for now.

Note also that if you set rights to dark after content is accessioned, the files will be removed from Stacks when the item is republished. I confirmed this by re-selecting dark rights on this item via Argo: https://argo.stanford.edu/view/druid:bb017bt0553

**Comment by peetucket** [comment]
Suggestion:

Pre-assembly should check current object rights and set shelve and publish to false for all files in contentMetadata if the rights are set to dark.
