### ISSUE TITLE
Proxy ticket:  Investigate SWAP index access discrepancies

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/pre-assembly#64]
Web archiving task for pre-assembly workcycle. 

For the examples provided in this query, two of three were resolved as of today, while the most recent report on the related ticket JIRA tickets belwo. [SWAP](https://github.com/sul-dlss/swap/) is an overlay of Stanford's [OpenWayback](https://github.com/iipc/openwayback/) instance running as a Java webapplication. 

### Failing Example in ticket [WARC-232](https://jirasul.stanford.edu/jira/browse/WARC-232) 
https://swap.stanford.edu/*/http://web.stanford.edu/dept/SUL/library/sunset-magazine/ returns 404 
while a specific example https://swap.stanford.edu/20171207191540/http://web.stanford.edu/dept/SUL/library/sunset-magazine/ is reachable. 

#### Gatt Example
https://swap.stanford.edu/20170413155237/http://gatt.stanford.edu/page/home -- Example resolved on 17 March 2018
https://swap.stanford.edu/*/http://gatt.stanford.edu/page/home -- Resolves correctly but reported as broken on 17 March 2018

#### Waseda Example
https://swap.stanford.edu/20170628171729/https://www.waseda.jp/fcom/soc/ -- Example resolved on 18 April 2018
https://swap.stanford.edu/*/https://www.waseda.jp/fcom/soc/ -- Resolves correctly, reported as broken 18 April 2018

**Comment by jmartin-sul** [comment]
this is a proxy ticket for maintenance work in another repository that we didn't get to.

@ndushay and @nullhandle, is this info captured elsewhere?  should i port this ticket to another github repo?

**Comment by jmartin-sul** [comment]
this is "in progress" on the pre-assembly waffle board at the moment because i'm in the process of dispositioning this proxy ticket.  AFAIK there is currently no work in progress on addressing the actual SWAP issue.

**Comment by jmartin-sul** [comment]
going to assume Jira issue WARC-232 covers this, and will close this issue.  @ndushay or @nullhandle, feel free to reopen if i'm closing this in error.
