### ISSUE TITLE
Add support for 'document' content type

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/pre-assembly#665]
The content type 'document' is now supported as the way to have PDFs render in the Mirador viewer. This content type should be added to preassembly so users can set it at accessioning time.

**Comment by jcoyne** [comment]
@andrewjbtw what should the resource type be for an object that is a 'document'?

**Comment by andrewjbtw** [comment]
The resource type is also 'document'. The info is somewhat buried here:

https://consul.stanford.edu/display/chimera/DOR+content+types,+resource+types+and+interpretive+metadata

**Comment by jcoyne** [comment]
Blocked by https://github.com/sul-dlss/assembly-objectfile/pull/44
