### ISSUE TITLE
Version mismatch errors for recent reaccessions

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/pre-assembly#667]
**Describe the bug**
Many items reaccessioned via preassembly since Friday are hitting version mismatch errors. 

These SMPL items were all submitted on Friday and are stuck in accessioning because of version mismatches.
https://argo.stanford.edu/catalog?f%5Bexploded_tag_ssim%5D%5B%5D=SMPL&f%5Bsubmitted_latest_date%5D%5B%5D=days_7&f%5Bwf_wps_ssim%5D%5B%5D=accessionWF%3Apreservation-ingest-initiated%3Aerror

**Expected behavior**
Pre-assembly has supported versioning for months, and I did not see any problems during the day on Friday, so this is a recent issue.

**Comment by andrewjbtw** [comment]
Note that many of the items in the above search are being fixed manually to keep content going through the accessioning pipeline. 

This item is being held back as an example of the error: https://argo.stanford.edu/view/druid:yy009ks9722

**Comment by andrewjbtw** [comment]
Additional context: the full pre-assembly job consists of these items
https://argo.stanford.edu/catalog?f%5Bexploded_tag_ssim%5D%5B%5D=Project+%3A+M2081+yakobson&per_page=50

Only some of them hit version mismatch while others went through without an error.

**Comment by jcoyne** [comment]
@andrewjbtw I believe the error is correctly being raised, as the objects in DOR don't have any workflow records from earlier accessioning and their versionMetadata indicates version 1.  However, the preservation servers already have MOABs:
```
[pres@preservation-catalog-prod-01 yy009ks9722]$ pwd
/services-disk11/sdr2objects/yy/009/ks/9722/yy009ks9722
[pres@preservation-catalog-prod-01 yy009ks9722]$ ls -lt
total 4
drwxrwxr-x 4 pres pres 4096 Apr  6  2017 v0001
```

**Comment by jcoyne** [comment]
One possibility is to prevent starting a workflow for a version of an object that already exists rather than clearing out the old workflow and starting over: https://github.com/sul-dlss/workflow-server-rails/blob/ac0bb9f196737db121944122c8b5fa9d035a50d3/app/services/workflow_creator.rb#L23. I believe having existing steps is an indicator that we're about to run into this version mismatch problem.

**Comment by andrewjbtw** [comment]
I think we'll need to do some analysis of the whole process from preassembly/assembly to accessioning before making that change. There's no user-facing interaction to create new versions explicitly when using preassembly. That's handled automatically, if a new version is needed. We're also trying to avoid users having to supply version numbers for each druid in a preassembly batch.

So if we prevented starting a workflow for if the a workflow already existed for that version, we'd still need the system to handle the version numbering and naming automatically.

**Comment by andrewjbtw** [comment]
There's a further complication here in that I think the workflow service version numbers are not actually matching the druid version numbers. If an object goes through assemblyWF 2 times and accessionWF 5 times (because metadata-only updates don't need assemblyWF), I think you'll end up with:

assemblyWF versions: 1,2
accessionWF versions: 1,2,3,4,5

Even if assemblyWF version 2 actually corresponds to druid version 3, 4, or 5.

**Comment by jcoyne** [comment]
@andrewjbtw the workflow versions should exactly match the druid versions, as that is what is used when creating a workflow: https://github.com/sul-dlss/argo/blob/099b90f2bbda05f90a98a4639b0c8830f056dbc9/app/controllers/workflows_controller.rb#L73

**Comment by andrewjbtw** [comment]
I must be seeing a lot of old workflow data where the versions do not line up correctly. For example, the two versions of assemblyWF on [this item](https://argo.stanford.edu/view/druid:bb261xs7846) are 1 and 2 but assemblyWF must have run on versions 1 and 3. Recent items do have the workflow versions lined up correctly.

In any case, I'm closing this issue because even though we don't know what happened to create these version mismatches, it doesn't appear to be recurring.
