### ISSUE TITLE
[PROXY] Images used for texture and normal map with 3D objects are not shelved

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/pre-assembly#677]
Proxy ticket for https://github.com/sul-dlss/assembly-objectfile/issues/30 since assembly-objectfile is not on the zenhub board. See that ticket for details.

PR: https://github.com/sul-dlss/assembly-objectfile/pull/31

**Comment by peetucket** [comment]
The proxied issue is closed.
