### ISSUE TITLE
Migrate 'prepare-content' script from lyberservices-scripts to pre-assembly

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/pre-assembly#682]
The 'prepare_content.rb' ruby script is in use by the Maps accessioning team, and needs to be migrated to allow the retirement of the lyberservices-scripts codebase and server it is deployed.  The pre-assembly codebase is a logical location as it has the required mount points.  The script is a simple ruby file that is invoked directly on the server and does not have any framework or other service dependencies (just needs access to mounts where the content is located).

Current script location: https://github.com/sul-dlss/lyberservices-scripts/blob/master/devel/prepare_content.rb

End user documentation to update: https://consul.stanford.edu/pages/viewpage.action?pageId=146704638

To migrate, we need to
- [x] copy this single ruby file into a new "devel" or existing "bin" folder
- [x] update the documentation to reflect its new location
- [x] ensure the maps accessioning team has access to get to the server (Megan Trott, Andria Olsen)
- [ ] test it with them

**Comment by jcoyne** [comment]
I'm confirming `andolson` and `andolson` have access to preassembly prod.

**Comment by peetucket** [comment]
I just noticed that the /maps mount on pre-assembly is read only, while it is read/write on lyberservices-prod.  Unless we stage this content to a different writable mount, it will fail.  The current documentation has the content staged in a subfolder on the /maps mount.  

So I think we either need to:

1. Request the /maps mount to be made read/write on sul-preassembly-prod

OR

2. Update the documentation and stage the content on a separate mount (e.g. the /dor mount and the /third-party mount both appear to be writable on sul-preassembly-prod.

#1 makes more sense to me unless there is a concern about it being writable.

Thoughts, @andrewjbtw ?

**Comment by andrewjbtw** [comment]
I don't know why the /maps preassembly mount would be read-only. I remember noticing that many of the mounts were read-only (not just maps) but not knowing why. I wonder if there was concern because of the shared nature of pre-assembly and the much larger user group with access to the server than for lyberservices, but this was all set up before my time.
