### ISSUE TITLE
Remove lyberservices-XXX servers as proxies to other services

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/pre-assembly#683]
Some services may still make calls to the lyberservices-XXX servers (which will be retired) which are then proxied onto the new locations (e.g. dor-services-app, suri, etc.).  We need to look through our apps and find the locations in shared_configs that still reference lybservices-XXX servers and update those to the new locations so that we can retire the proxies.

### Proxy to suri

See issue sul-dlss/suri-rails/issues/89

**Comment by jcoyne** [comment]
I'm fairly certain only the workflow is proxied.

**Comment by jmartin-sul** [comment]
> I'm fairly certain only the workflow is proxied.

i believe pres robots uses lyberservices to proxy requests to common-accessioning.  i have a couple shared configs PRs mean to change that, but they stalled out because i haven't gotten around to following up with ops to make sure firewall stuff is configured to allow the connection directly.

**Comment by jcoyne** [comment]
@jmartin-sul common-accessioning is not a service and thus, doesn't accept requests.

**Comment by ndushay** [comment]
Created issue sul-dlss/operations-tasks/issues/2259 for our VMs to be able to access workflow-services boxes.

**Comment by ndushay** [comment]
Created issue sul-dlss/operations-tasks/issues/2260 for our VMs to be able to access suri-rails boxes.

**Comment by jmartin-sul** [comment]
> @jmartin-sul common-accessioning is not a service and thus, doesn't accept requests.

ah, yeah, good clarification.  it's actually not a web request, pres robots seems to be [running a tarpipe command via `ssh`](https://github.com/sul-dlss/preservation_robots/blob/f45a19c78ab3ae7646f4210e21c22ec1991947a5/lib/robots/sdr_repo/preservation_ingest/transfer_object.rb#L22-L38) on [common-accessioning](https://github.com/sul-dlss/preservation_robots/blob/cacc51a80ed7d5fa24c67593fa9ef75799fa51fa/config/settings.yml#L15-L18).  "connection" would've been better word choice than "request".

filed https://github.com/sul-dlss/operations-tasks/issues/2261

**Comment by jcoyne** [comment]
@jmartin-sul if it's doing SSH connection I'm not sure it's proxying, is it?

**Comment by jmartin-sul** [comment]
> @jmartin-sul if it's doing SSH connection I'm not sure it's proxying, is it?

good point!  likely not.  still, a lyberservices dependency where the functionality could be provided by another existing VM.

**Comment by ndushay** [comment]
We are almost done with fixing deployed apps (via shared_configs) NOT to use lyberservices as proxy for workflow service.  It is ticketed here:  sul-dlss/operations-tasks/issues/2259 .   There is one VM (sdr-api-qa) that still needs access to be opened up, but everything else has access to workflow services and shared_configs have been set up to use the workflow service urls directly.

**Comment by jmartin-sul** [comment]
one more straggler -- preservation_robots had to switch back to lyberservices for its tarpipe command for the `transfer_object` method, because for some reason, its workers are unable to connect to dor-services-app.  troubleshooting this with kam, hope to have it resolved soon.

**Comment by ndushay** [comment]
@jmartin-sul I am closing this ticket about lyberservices VMs serving as proxies.  It seems like pres-robots may still have an issue -- I would encourage you to file a ticket in pres robots about it and get it in the ready column, if it's not yet resolved.

**Comment by jmartin-sul** [comment]
> @jmartin-sul I am closing this ticket about lyberservices VMs serving as proxies. It seems like pres-robots may still have an issue -- I would encourage you to file a ticket in pres robots about it and get it in the ready column, if it's not yet resolved.

discussed in standup, but for posterity:  i re-opened the related ops ticket, and will continue debugging with kam.  he suggested another possible debug info flag for the ssh command, but i haven't had a chance to try it yet.
