### ISSUE TITLE
Failed discovery jobs should show up in the pre-assembly UI

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/pre-assembly#695]
Currently if a discovery job end up failing, you can only see this by looking in resque - the user is not given any information in the pre-assembly UI.  To them, it simply looks like the job is still running.  For a long running job, it would not be obvious if it failed or is really still running.  It would be nice to change the status of the pre-assembly job to failed in the pre-assembly UI so the user can at least know it failed.

See also #940.  Pre-req: #535 

Example failed job in stage:

https://sul-preassembly-stage.stanford.edu/resque/failed/discovery_report_failed
https://sul-preassembly-stage.stanford.edu/job_runs/308

**Comment by mjgiarlo** [comment]
May not require full UI/UX design but could benefit from specification / discussion of how this should look.

**Comment by ndushay** [comment]
Peter has been working in PR #932 to add more info to the "status" column;  I would have thought THIS would be the ticket to attach to PR 932

**Comment by peetucket** [comment]
Yes, working on adding a status column and display in #932, though for now it will not throw discovery reports into the failed state (in that PR anyway), though as far as UI display goes, it will cover it when we do.  So yes, I think this specific ticket can be closed by #932 as well.  #936 is the new work to put it an error state.
