### ISSUE TITLE
Differentiate between public and private methods

### ISSUE THREAD

**Issue by atz** [sul-dlss/pre-assembly#70]
An 850-line class (in addition to not existing, also) should not have ALL `public` methods.  

Clarify our class' public API(s) by segregating internal methods as `private`.

**Comment by atz** [comment]
This has begun.  Given the `YAML_PARAMS`/`INIT_PARAMS` style of the old classes, it would also be good to sort out which attributes **actually** need to be accessors and which should be regular readers.

**Comment by jmartin-sul** [comment]
i think this is now done, as of #402?  or at least, all the models seem to have proper public/private differentiation.

closing this, but feel free to reopen if that seems wrong.
