### ISSUE TITLE
Pre-assembly jobs stalling without failing or stopping

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/pre-assembly#717]
**Describe the bug**
Some preassembly jobs over the past few weeks have failed silently. They still show up on the resque console and in htop if you look at the server, but no work is actually happening. I've been able to tell that no preassembly work is happening by checking the log for the preassembly job and seeing that no new content from the job is being accessioned. 

It's not clear what exactly is causing this, but I've only seen it with jobs that have run for a day or more. Sometimes jobs run for multiple days in a row successfully, other times they don't. 

**Expected behavior**
Preassembly jobs should fail visibly if they stop doing work, so that you can tell from resque or the preassembly interface itself that it has failed.

**Additional context**
There are three preassembly jobs showing in resque right now: https://sul-preassembly-prod.stanford.edu/resque/overview

These three jobs should all be killed and not restarted because the content has completed accessioning via later preassembly runs.

**Comment by jcoyne** [comment]
It looks like this had an open file handle and the filesystem got yanked out from under it:
```
$ lsof -p 19518|grep contentMetadata
ruby    19518 preassembly   12w  unknown                               /dor/assembly/zq/586/rn/3938/zq586rn3938/metadata/contentMetadata.xml (stat: No such file or directory)
```

**Comment by jcoyne** [comment]
```
I ran the following:
```
gdb -p <pid>
```

Then pasted in this definition:
```
define r_eval
  call (void)rb_p((unsigned long)rb_eval_string_protect("File.open('/tmp/caller.out', 'a') { |f| begin; f.write $arg0; f.write('\n'); rescue => ex; f.write ex.inspect; f.write('\n'); end }",(int*)0))
end
```

and then ran:
```
r_eval Kernel.caller.join('\n')
```

This wrote the backtrace to `/tmp/caller.out` which showed:

```
eval:1:in `open'
eval:1:in `write_nonblock'
<internal:prelude>:131:in `__write_nonblock'
<internal:prelude>:131:in `write_nonblock'
/opt/app/preassembly/pre-assembly/shared/bundle/ruby/2.6.0/gems/resque-pool-0.7.1/lib/resque/pool.rb:170:in `awaken_master'
/opt/app/preassembly/pre-assembly/shared/bundle/ruby/2.6.0/gems/resque-pool-0.7.1/lib/resque/pool.rb:165:in `block in init_sig_handlers!'
/opt/app/preassembly/pre-assembly/shared/bundle/ruby/2.6.0/gems/mini_exiftool-2.10.0/lib/mini_exiftool.rb:404:in `read'
/opt/app/preassembly/pre-assembly/shared/bundle/ruby/2.6.0/gems/mini_exiftool-2.10.0/lib/mini_exiftool.rb:404:in `block in run'
/usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/open3.rb:219:in `popen_run'
/usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/open3.rb:101:in `popen3'
/opt/app/preassembly/pre-assembly/shared/bundle/ruby/2.6.0/gems/mini_exiftool-2.10.0/lib/mini_exiftool.rb:393:in `run'
/opt/app/preassembly/pre-assembly/shared/bundle/ruby/2.6.0/gems/mini_exiftool-2.10.0/lib/mini_exiftool.rb:156:in `load'
/opt/app/preassembly/pre-assembly/shared/bundle/ruby/2.6.0/gems/mini_exiftool-2.10.0/lib/mini_exiftool.rb:115:in `initialize'
/opt/app/preassembly/pre-assembly/shared/bundle/ruby/2.6.0/gems/assembly-objectfile-1.10.0/lib/assembly-objectfile/object_fileable.rb:91:in `new'
```

So this indicates a bug in resque-pool where it can't awake the master process.   This may be because the master process was killed (possibly by a deploy). 
```

**Comment by vivnwong** [comment]
Replacing resque-pool with sidekiq will not fit well within the First Responder's work. Talked to Andrew and he agreed to handle the resque-pool replacement in a maintenance WC.

**Comment by ndushay** [comment]
Possible that this is not happening in this way any more ... 

We need a biiiig batch such as newspaper content that Mary Ellen runs in order for this to potentially be triggered again.

problems:  
- the log shows no progress; need to kill app and restart workers again.  (Peter added a progress log)
- we get zombie processes when this happens.
- need an easier way to restart (? maybe)

**Comment by ndushay** [comment]
We are hopeful that PR #532 will address this.

**Comment by ndushay** [comment]
marked blocked until we know if addressing issue #961 is sufficient (PR #965)

**Comment by ndushay** [comment]
We believe this has been addressed by Peter adding the state machine to show the status of running jobs.
