### ISSUE TITLE
"Process : Content Type : Map" should map to the "image" resource type

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/pre-assembly#718]
**Describe the bug**
Older objects that have been registered as "map" content type are being assigned the "file" resource type when accessioned via preassembly using the "image" content structure. This is the incorrect resource type. The "map" content type should get the "image" resource type.

Note that this seems to affect only objects registered in the time before the registration process created a contentMetadata datastream. Newly registered objects will get a stub contentMetadata and appear to get accessioned correctly. 

There are as many as 800 registered "map" objects that may have this issue when they get accessioned in the future:
https://argo.stanford.edu/catalog?f%5Bprocessing_status_text_ssi%5D%5B%5D=Registered&f%5Btag_ssim%5D%5B%5D=Process+%3A+Content+Type+%3A+Map

**User impact**
The "file" resource type does not trigger jp2 creation. This means that users cannot just correct the content type in Argo because no jp2 files will be present for display. So when this happens, the user remediation is a multi-step process:

1. Open objects in Argo
2. Change resource type to image
3. Close object
4. Run preassembly again

**To Reproduce**
1. Go to a registered map object that does not yet have a contentMetadata datastream. Here is an example in stage:
https://argo-stage.stanford.edu/view/druid:hs947tw5381
2. Accession a tiff for that druid via preassembly using the "image" content structure
3. See that resource type is set to file

**Expected behavior**
The "map" content type should function similarly to the "image" content type.

**Comment by jcoyne** [comment]
Kicked off a job on argo to remediate this data. It should take 3-4 days to complete.  Monitoring with:

https://sul-solr-a.stanford.edu/solr/argo_prod/select?rows=0&fq=exploded_tag_ssim%3A%22Process%20%3A%20Content%20Type%22%20processing_status_text_ssi%3ARegistered%20-content_type_ssim%3A[*%20TO%20*]

**Comment by jcoyne** [comment]
I’ve converted all the registered objects to the new format. There are only 15 records that we didn’t convert. 
14 were “Manuscript” types and the other was this record: https://argo.stanford.edu/view/druid:yv477bg1793 which has a very messed up contentMetadata.
