### ISSUE TITLE
[Hold for file-level rights to be done] Replace resque-pool and resque with sidekiq

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/pre-assembly#719]
I believe this would prevent #717 
Additionally it would provide consistency with the direction of other dlss projects.

NOTE:  **retries** _must_ be set to **false**

**Comment by ndushay** [comment]
We need to ensure we understand why discovery reports and preassembly jobs stop or hang before we want them to retry.  But we could switch to sidekiq with retry set to false until then.

![image](https://user-images.githubusercontent.com/96775/171919212-858b2445-86e1-497d-b69d-7488d32b199d.png)

**Comment by ndushay** [comment]
@andrewjbtw @peetucket I think if we switch to sidekiq with `retry: false` as our starting point, we can turn on retry when we've got a better handle on when to allow sidekiq to retry.

Currently, we have the full "run" of n objects as the job unit going through preassembly queues. 

I think we want to leverage sidekiqs automatic retries in pre-assembly, once we do a better job of error handling

**Comment by ndushay** [comment]
@jcoyne:  can you please flesh this out?

We want to switch from resque to sidekiq because:
- sidekiq has automatic retries with a backing off timetable built in
- ???

**Comment by ndushay** [comment]
Let's do ONE of this ticket or #974 at a time.

**Comment by ndushay** [comment]
Latest:  Waiting on John to finish his performance improvements PR (currently #965) and get it merged, as well as other active work that might be made more difficult with switching to sidekiq

**Comment by ndushay** [comment]
Rob is away until 6/27

**Comment by ndushay** [comment]
the action for this ticket is to work with ops to get sidekiq requirements on preassembly VMs (see also #974), and then to either work with PR #927
