### ISSUE TITLE
Support accessioning agreement objects

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/pre-assembly#743]
We should add support for accessioning agreements to preassembly. Currently, pre-assembly only supports accessioning the item object type. 

Agreements are a special SDR object type. They are similar to items in that they contain both metadata and content files, and are unlike APOs and Collections, which consist only of metadata. The current process for creating agreements involves a complex multi-step process of using Hydrus for the initial upload and then editing datastreams in Argo to turn the object into an agreement and detach it from Hydrus. Being able to accession agreements in pre-assembly will allow us to retire that process.

**Comment by justinlittman** [comment]
Can you describe the function / purpose / use of the agreement? And provide some examples?

**Comment by jcoyne** [comment]
An agreement is just a type of item that has "agreement" in the IdentityMetadata objectType field.  Examples: https://argo.stanford.edu/catalog?f%5BobjectType_ssim%5D%5B%5D=agreement

**Comment by andrewjbtw** [comment]
Agreements are the human-readable documents that govern the objects in SDR. The APOs are supposed to be machine-readable implementations of the agreements, at least in terms of rights. More about agreements here: https://consul.stanford.edu/display/SDRA/About+SDR+agreements

In terms of the system, every APO has to refer to an agreement object. It's possible to add new APOs to an existing agreement, but if there's a new agreement it has to be created before the new APO that would go with it. When you created an APO, you're given a choice of agreements to use in a dropdown on the Register APO form. 

All agreements end up referring to the Internal System Objects APO: https://argo.stanford.edu/view/druid:hv992ry2431 I believe this APO exists to get around the chicken and egg problem of every object in SDR needing an APO and every APO needing an agreement.

**Comment by aaron-collier** [comment]
More information from @andrewjbtw:

```
I think some analysis is needed. I don’t know how cocina accounts for agreements. Right now the way to make them is to literally type “agreement” in place of “item” in the identityMetadata datastream

We need to either support them in preassembly (which only does items) or take the radical step of allowing people to add files in Argo itself. The radical step would be:
- make a create agreement form
- upload the agreement files to that form
- trigger accessioning from submitting that form

Currently, the agreement process starts in Hydrus and then goes through a series of datastream edits to become an agreement.
```

**Comment by andrewjbtw** [comment]
A ticket for creating agreement objects is here: https://github.com/sul-dlss/argo/issues/2357

**Comment by ndushay** [comment]
This ticket is about UPDATING existing agreement object via pre-assembly.

**Comment by peetucket** [comment]
I am doing some analysis here.  I think there are a few changes needed:

1. The existing ticket (now in progress) that allows agreement objects to be registered in Argo: sul-dlss/argo#2357
2. Examining this example agreement object (https://argo.stanford.edu/view/druid:bn720jm8470), it appears it uses "file" type contentMetadata.  Thus, we need to ensure that the "agreement" object type in cocina (`Cocina::Models::Vocab.agreement`) maps to `:file` type contentMetadata here:  https://github.com/sul-dlss/pre-assembly/blob/main/app/lib/pre_assembly/digital_object.rb#L50-L59  That is easy.
3. Since agreements are dark, ensure the we end up with file attributes of `preserve=true publish=false shelve=false`.  A quick scan of the code suggests that although we detect dark objects, but I'm not convinced we do the right thing when generating contentMetadata.  It may end up assigning file attributes incorrectly, so this would need to be corrected if so.  This is where most of the work is likely to be.

I don't think any other changes would be needed since pre-assembly doesn't do much else other than stage files and generate contentMetadata.

**Comment by peetucket** [comment]
Ok, digging some more through the code and tracing it over the `assembly-objectfile` gem, maybe it will do the right thing with the file attributes for dark objects.  There is even a test for this: https://github.com/sul-dlss/pre-assembly/blob/main/spec/features/dark_file_object_spec.rb

I can double check this works after making the change in #2 above.

**Comment by andrewjbtw** [comment]
I'm also not quite sure it does the right thing for dark objects. We did make a dedicated effort to do the right thing and for a long time it did, but in testing rights on stage recently it seemed to be allowing "shelve=yes,publish=yes" on files. I made a note to myself to check since that wasn't what I was testing at the time. 

But since dark does mean no purl, and stacks will block downloads in that situation, at least the files aren't actually made accessible.

**Comment by peetucket** [comment]
> I'm also not quite sure it does the right thing for dark objects. We did make a dedicated effort to do the right thing and for a long time it did, but in testing rights on stage recently it seemed to be allowing "shelve=yes,publish=yes" on files. I made a note to myself to check since that wasn't what I was testing at the time.
> 
> But since dark does mean no purl, and stacks will block downloads in that situation, at least the files aren't actually made accessible.

It looks like it did the correct thing for me in testing.  I tested two agreements with my branch of pre-assembly: one was an existing agreement and one was a new agreement registered with the new form Justin is working on.  Both generated file type content metadata with the expected publish/preserve/shelve attributes and versioned as expected. 

https://argo-stage.stanford.edu/view/druid:xd706rn1742
and
https://argo-stage.stanford.edu/view/druid:xd706rn1742
