### ISSUE TITLE
Support reading order for books

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/pre-assembly#759]
part of https://github.com/sul-dlss/argo/issues/2427

We offer the menu options at registration to set the reading order for books with the following content type choices

- Book (ltr)
- Book (rtl)

Preassembly does not respect these choices and only offers one option for book, which ultimately ends of as ltr. Preassembly should

1. Show menu options for "Book (ltr)" and "Book (rtl)"
2. Write the appropriate contentMetadata to include the <bookData> element that governs reading order

For the <bookData> element, see the Chimera documentation for content types: https://consul.stanford.edu/display/chimera/DOR+content+types,+resource+types+and+interpretive+metadata

**Comment by peetucket** [comment]
@andrewjbtw it looks we need to add a `<bookData>` tag to `contentMetadata` according to https://consul.stanford.edu/pages/viewpage.action?spaceKey=chimera&title=DOR+content+types%2C+resource+types+and+interpretive+metadata

I have a PR now that teachers the assembly-objectfile gem how to do this: sul-dlss/assembly-objectfile#54 

This would add the <bookData> node for all books going forward (coming from pre-assembly), even if they have the default value.  Does this sound reasonable?

The next step would be to add a new drop-down menu in pre-assembly to specify the book order.

For Argo, it looks like the 'content type' of 'book (ltr)' or 'book (rtl)' doesn't do anything with content Metadata but instead just makes the settings at the the cocina-model level.

**Comment by peetucket** [comment]
It looks like the cocina modeling finds this direction in contentMetadata: 

FROM FEDORA: https://github.com/sul-dlss/dor-services-app/blob/aaf52051801d2d4de8fc3734e3579ec3c3388254/app/services/cocina/from_fedora/dro_structural.rb#L60

TO FEDORA: https://github.com/sul-dlss/dor-services-app/blob/aaf52051801d2d4de8fc3734e3579ec3c3388254/app/services/cocina/to_fedora/content_metadata_generator.rb#L40-L46

However, the from case uses `readingDirection` and the to case uses `readingOrder`.  One of these seem wrong.  The consul page above specifies `readingOrder`, so perhaps that is what it should be?  Do you happen to know?

**Comment by andrewjbtw** [comment]
It should be `readingOrder` based on both the Consul page and examples on the purl, which all use that form.

I assume the default is left-to-right? I think it will be ok to set that explicitly in the future since Cocina always declares it. For books that don't have it right now, it shouldn't change things since a lack of `<bookData>` seems to be automatically interpreted as left-to-right. Probably best to make a few examples on stage though.

**Comment by peetucket** [comment]
OK, the code is certainly cleaner and easier to maintain if we just add always even if its the default.  The changes I am making will only affect objects with brand new contentMetadata.

**Comment by peetucket** [comment]
And yes, default is left to right...

**Comment by peetucket** [comment]
Closed by #758
