### ISSUE TITLE
async environment setup

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#79]
get redis etc up and running

**Comment by jmartin-sul** [comment]
- talk to tony and figure out where to file this ticket
- file the ticket

**Comment by atz** [comment]
Place to file ops requests:
https://github.com/sul-dlss/operations-tasks/issues

**Comment by jmartin-sul** [comment]
filed ticket for spinning up Redis: https://github.com/sul-dlss/operations-tasks/issues/1742

**Comment by jmartin-sul** [comment]
@atz, is there any other setup you can think of that falls under this ticket?

**Comment by jmartin-sul** [comment]
@atz says:  actual invocation of resque pool happened in puppet, but doesn't need separate ticket, should just fall out of worker implementation.

**Comment by jmartin-sul** [comment]
redis has been installed on the VMs, and https://github.com/sul-dlss/operations-tasks/issues/1742 has been closed.

closing this, since it sounds like the rest will naturally fall out of worker implementation.
