### ISSUE TITLE
pretty print discovery report JSON for download

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/pre-assembly#795]
**Is your feature request related to a problem? Please describe.**
Discovery reports can be hard to read, particularly for people who are not familiar with JSON and/or do not have an application installed that can do syntax highlighting and pretty printing.

The more training of new users I do, the more this comes up.

**Describe the solution you'd like**
Pretty printed JSON reports would be easier to read in a text editor.

~~There's already a ticket for formatting discovery reports for online display: https://github.com/sul-dlss/pre-assembly/issues/257 This has not yet made it into a maintenance workcycle, as bug fixes, work to decouple from Fedora, and functional improvements have taken priority. Pretty printing could make a short-term compromise.~~

**Describe alternatives you've considered**
Starting to compile some suggestions for editors that apply some formatting to JSON. I've suggested using Firefox to open the discovery reports, as it will do pretty printing, but not everyone uses Firefox or even has it installed.

**Comment by ndushay** [comment]
marking blocked until we know if there's an alternate formatted report approach

**Comment by ndushay** [comment]
The action for this ticket is to make the downloaded discovered report have pretty print formatting (JSON pretty print or whatever) instead of being a single line.
