### ISSUE TITLE
vet application for amenability to becoming standardized async worker DLSS web app

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#80]
in particular, we'd like to wire things up so that the pre-assembly work is done by resque workers, using code that's entirely in the ruby/rails application in which the workers live.  this will make it much easier to manage dependencies, maintain the code going forward, run the application on its own dedicated VM instead of lyberservices, and all the other nice sustainable practices we've gotten accustomed to the last few years.

- class variables / thread safety (e.g. excise uses of the former to support the latter)
- logging (#78)
- dependency loading: source of memory leaks

hope is that railsifying the app should solve a lot of this, since it does dependency auto-loading.

**Comment by jmartin-sul** [comment]
more:
* hardcoded paths (and other hardcoded configuration)
* shelling out to other scripts, especially other DLSS applictions

**Comment by atz** [comment]
Hardcoded paths enumerated in #91.

Searching for three kinds of shelling out:
- `system` calls: no novel uses (only generated rails stubs)
- `open` and related calls: none found
- backticks: some found

In `bin/download_object`:
```ruby
  copy_command = "rsync -vOlt lyberadmin@stacks.stanford.edu:#{stacks_path} #{filename}"
  `#{copy_command}`
```

**Comment by jmartin-sul** [comment]
found the same things that @atz beat me to the punch on.

for that one script that uses backticks... after looking at it more closely, i'd be inclined to move that to dor-scripts, and maybe make it clearer that the intent is to have it run from a user's laptop.

**Comment by jmartin-sul** [comment]
things we wanted to vet in this ticket
- [ ] class variables / thread safety (e.g. excise uses of the former to support the latter)
- [ ] logging (#78)
- [ ] dependency loading: source of memory leaks
- [ ] hardcoded paths (and other hardcoded configuration) (#91)
- [x] shelling out to other scripts, especially other DLSS applictions
  - seems like we're good on this front:  only one script remains that does this, and it doesn't seem like we need to maintain its functionality in this repo going forward.

**Comment by jmartin-sul** [comment]
we know that we need to disentangle configuration loading/validation from the usage of said configuration fields in the application (#77), so that's not an unknown, and thus not part of this ticket.

**Comment by jmartin-sul** [comment]
i only found a small amount of obvious class variable usage:
```sh
$ git grep "@@"
lib/pre_assembly/druid_minter.rb:    @@druid = 'druid:aa000bb0000'
lib/pre_assembly/druid_minter.rb:      String.new(@@druid)
lib/pre_assembly/druid_minter.rb:      @@druid.next!
lib/pre_assembly/logging.rb:      @@log       ||= Logger.new(log_file)
lib/pre_assembly/logging.rb:      @@log.level   = LEVELS[:info]
lib/pre_assembly/logging.rb:      @@log.formatter = proc do |severity, datetime, _progname, msg|
lib/pre_assembly/logging.rb:      @@log.add Logging::LEVELS[severity], msg
```

i didn't turn up any relevant uses of `self.class` or class extension for variable declaration:
```sh
$ git grep "self.class"
lib/pre_assembly/bundle.rb:      self.manifest_rows = object_discovery[:use_manifest] ? self.class.import_csv(manifest) : []
$
$ git grep "class.*self"
$
```

**Comment by jmartin-sul** [comment]
a quick grep seems to indicate that all the in method `require` statements are gone too, which is the last thing that was unchecked.  all the remaining `require` statements seem to be in reasonable places.

this investigation seems to be done, closing the ticket.
