### ISSUE TITLE
prevent discovery report jobs from going stale

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/pre-assembly#816]
**Describe the bug**
In the past couple of months, a few long-running discovery report jobs have stopped making progress while still running on the server. When this happens, the job is visible in the resque console and with `ps` on the server, but there's no indication that any progress is being made. 

Preassembly and discovery report jobs keep a running log of which druids have been processed, so you can tell if they are still making their way through a batch. When a job appears to go stale, this log stops getting updated.

**To Reproduce**
It's hard to intentionally cause the issue but it seems like it might correspond to when preassembly is redeployed. The jobs that have gone stale have run successfully when run later in the week, but stalled if dependency updates were deployed while the job was running. That seems to have happened with https://github.com/sul-dlss/pre-assembly/issues/815

The problem seems to affect discovery reports more than preassembly jobs but that might be a coincidence, since this has not happened often.

**Expected behavior**
A preassembly or discovery report job should either finish or fail with an error. A failed job is easier to retry than a stale job.

**Additional context**
The problem doesn't seem to be the batch size per se because the same jobs have so far finished when run later in the week. But the longer a job runs, the greater the risk it could be interrupted. So in practice the jobs I've seen go stale have all had thousands of druids in them.

**Comment by ndushay** [comment]
See also #717

**Comment by andrewjbtw** [comment]
Closing this ticket as not actionable.
