### ISSUE TITLE
Cocina::Models::UnknownTypeError: Unknown type: 'https://cocina.sul.stanford.edu/models/media'

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/pre-assembly#857]
## Backtrace

    line 100 of [PROJECT_ROOT]/app/lib/pre_assembly/digital_object.rb: object_type
    line 61 of [PROJECT_ROOT]/app/lib/pre_assembly/digital_object.rb: content_md_creation_style
    line 144 of [PROJECT_ROOT]/app/lib/pre_assembly/digital_object.rb: create_content_metadata

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/52900/faults/84521339)

**Comment by ndushay** [comment]
@justinlittman @andrewjbtw 

I think this is from a long running preassembly job, where the cocina-models changed this morning while it was still running and maybe there was a cocina models mismatch between this job and DSA. (that is, this job was using an older dor-services-client, which no longer worked for the current dor-services-app).   The job in question is 8796 and, the current job number are 88nn, and I remember Andrew mentioning a long running preassembly job.

is this plausible?  

Does someone need to check with @oceanofsound  ?

**Comment by andrewjbtw** [comment]
@ndushay I think you're right. I've restarted this job and am waiting to see what happens when the next druid finishes the content staging. From the log it looks like the most recent druid started going through preassembly before the prod deploy and then finished afterwards.

**Comment by andrewjbtw** [comment]
Preassembly just finished successfully on the druid that failed earlier, so I'm closing this ticket.
