### ISSUE TITLE
Hardcoded paths, implicit dependencies

### ISSUE THREAD

**Issue by atz** [sul-dlss/pre-assembly#91]
13 lines of code or config (not comments) hardcode `/dor/preassembly` locations:
- /dor/preassembly/ap_tei
- /dor/preassembly/gould_log.yaml
- /dor/preassembly/remediation/revs_jp2
- /dor/preassembly/remediation/scripts/revs_update_images_remediation.rb
- /dor/preassembly/remediation/scripts/revs_update_mods_remediation.rb
- /dor/preassembly/remediation/scripts/update_mods_remediation.rb
- /dor/preassembly/remediation/scripts/update_salt_document_types_remediation.rb
- /dor/preassembly/remediation/scripts/update_salt_exhibit_date_remediation.rb
- /dor/preassembly/revs_craig_log.yaml
- /dor/preassembly/revs/revs_ludvigsen-1971_log.yaml
- /dor/preassembly/revs/revs_ludvigsen-1972_log.yaml
- `File.join('/dor/preassembly/revs/', name_without_extension + "_log.yaml")`

5 more reference `/dor/staging` locations:
- /dor/staging/Revs/druids.csv
- /dor/staging/Revs/Ludvigsen/
- /dor/staging/Revs/mods_template.xml
- /dor/staging/Revs/PilotProject/content
- /dor/staging/Revs/revs_template_preassembly_yaml_file.yaml

6 non-comment lines reference `/dor/assembly`

A handful more lines reference `/dor/workspace`.  

Point being, none of these are included or modeled by this application, so the application's reliance on 30+ hardcoded paths, including for its own **actual code** is a blocker to a clean, new deployment.  Effectively, **this application doesn't even know what it is** without those files, and those files appear not to be in version control anywhere.

Most of these files/paths don't exist in all environments, meaning they are effectively unverified and untestable.  We will need some decisions about what gets carried forward and what gets cut.

**Comment by peetucket** [comment]
To be more specific, these reference files on shared mounts, which exist in all currently deployed environments (including on the new pre-assembly boxes), so its technically not just in production.  Obviously not local to your laptop or to github, which does it make not possible to test.  Some of these scripts are likely one-off in utility and do not benefit from being kept around.  Others may have some utility for future scripty/one-off/data remediation needs.  Perhaps we can have some strategy where scripts like those in the "devel" folder are moved to a separate "scripty" repo, which is configured as needed but does not have the same code testing/maintenance expectations of code like pre-assembly.

**Comment by atz** [comment]
From comparing side-by-side yesterday, I do not find the `stage` mounts to be as populated as the `production` ones generally, and specifically with the files enumerated.

**Comment by SaravShah** [comment]
Seems like we removed a lot of these via deleting scripts.

**Comment by SaravShah** [comment]
`/dor/staging/` appears twice in the README.
`/dor/preassembly/`appears 4 times in the README, twice in  TEMPLATE.YML and  once in reg_example.yml. 

i think by deleting all of the cruft code/scripts this is now not needed?

**Comment by jmartin-sul** [comment]
sounds good to me, closing
