### ISSUE TITLE
EPIC: File-level rights specification

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/pre-assembly#910]
e.g. for Media, the program is downloadable but the specific videos are not (?)

Possibly use native structural cocina-model rather than contentMetadata to allow this

- ~~Can this be expressed in contentMetadata.xml?~~ - no
- Should preassembly be converted to native cocina?  
- Can preassembly be in cocina while assembly is in xml?
- Can assembly be ok with either cocina or xml?

**Comment by ndushay** [comment]
@andrewjbtw - is this done?

**Comment by andrewjbtw** [comment]
I haven't figured that out yet.

**Comment by andrewjbtw** [comment]
Preliminary answer: looks like there's a PR I need to test: https://github.com/sul-dlss/pre-assembly/pull/1049

**Comment by andrewjbtw** [comment]
I've tested and approved #1049 - including setting file level rights via the Argo-style manifest - so we can close this soon.

**Comment by ndushay** [comment]
@andrewjbtw can this epic ticket for file-level rights be closed?

**Comment by andrewjbtw** [comment]
You can close the epic. The work isn't merged but can be finished separately.
