### ISSUE TITLE
Discovery Report yml LOG should show success/failure for each object

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/pre-assembly#917]
Currently the discovery report either succeeds or it doesn't get generated at all.

It would be helpful if, at least for the failure case, there was data showing which objects failed or other failure information.  Currently the documentation says "look at the resque UI".  The shared data could be a simple log with the druid and the status of success or failure.  At a minimum it would be helpful to at least have a list of the druids that failed.  

Bonus points if there can be some sort of failure cause message - maybe the exception thrown or whatever.

**Comment by ndushay** [comment]
It's possible there is some partially implemented code along these lines;  @peetucket may be able to illuminate.  (See batch.rb and Logging.rb  (which uses evil class variables)

**Comment by ndushay** [comment]
@andrewjbtw do you want the log file to be .yml, or a csv, or ???   Can you provide a sample of what you would like?

**Comment by peetucket** [comment]
The discovery report log actually exists and is created in YAML format to match what preassembly jobs produce.  I do not think we want to change this format, as it is useful for restarting and for consistency.  We could also produce a CSV if needed though.  There is separate work to allow the YAML log file to be downloaded at least (which it currently is not able to be). See #939

**Comment by ndushay** [comment]
Action:  THIS ticket will be to include these additional things in the yml log file:

for each druid:
- success/failure
- if failure, provide error message, if not too hard.  (if difficult, talk to Naomi and let's make more tickets for that)

**Comment by ndushay** [comment]
@peetucket why did this ticket move from READY to BACKLOG?   Is it no longer useful?

**Comment by peetucket** [comment]
Sorry, that was a mistake, moving back to ready.
