### ISSUE TITLE
prepare for Redis 5.0.0 - address warning

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/pre-assembly#929]
This is from `resque-pool.stderr.log`:

```
Pipelining commands on a Redis instance is deprecated and will be removed in Redis 5.0.0.

redis.pipelined do
  redis.get("key")
end

should be replaced by

redis.pipelined do |pipeline|
  pipeline.get("key")
end

(called from /opt/app/preassembly/pre-assembly/shared/bundle/ruby/3.0.0/gems/redis-namespace-1.8.2/lib/redis/namespace.rb:530:in `namespaced_block'}
```

See https://github.com/resque/redis-namespace/issues/189 and the begging for a new release of the gem at  https://github.com/resque/redis-namespace/pull/190

This will block our upgrade to the redis gem 5.0

Can this be fixed by updating one or more gems?  redis-namespace comes from resque gem ...

**Comment by jcoyne** [comment]
If we move to sidekiq, do we still have this problem?

**Comment by andrewjbtw** [comment]
Is this closeable now that we're on sidekiq?
