### ISSUE TITLE
Discovery report should go into an error state if any single object has an error

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/pre-assembly#936]
**This ticket is about what to do when there is an object that has an error, but there is no Ruby exception interrupting the processing of the entire discovery report.**

If discovery report detects a problem with an object, it should put the job _"state"_ into (eg "completed with errors") ... and keep processing.

The discovery report should include the failed object and info about the failure.

see also #917

**Comment by ndushay** [comment]
We also want a state for "errored out" , so discovery report should be able to get in these states:

- waiting
- running
- complete
- complete with errors <-- tweak "error" state to mean this
- errored out  <---  new state

**Comment by ndushay** [comment]
@peetucket I'm assigning this to you because I think you're already working on it in PR #956.
