### ISSUE TITLE
report on (discovery report) usage

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/pre-assembly#948]
Please gather this data (and anything else you think would be useful)

for discovery reports (and pre-assemble runs, if they come along for free and are analyzed separately)
- number of objects in discovery report (ideally, number desired by user, but that may be hard.  Will settle for number that didn't error  ... please label appropriately)
- How long did discovery report take (I hope we have this) - elapsed time;  more if we can get it
- Number of files (total, but would love per object if available)

It would be great to have this in visual form as well as tabular, but it's okay to have a .csv that we can plot ourselves.

- number of objects in discovery report, as a histogram
- plot number of objects against elapsed time for report
- plot number of files against elapsed time for report
etc.

diff report:
- how often is file_manifest.csv used ... and by whom?  (as opposed to manifest.csv)

**Comment by ndushay** [comment]
first action to be taken:  look for the interesting bits we can pull from the database:

- user (sunet_id) with counts of job_runs by job_type and by using_file_manifest

maybe broken into groups by year (from job_runs.updated_at dates?)

**Comment by peetucket** [comment]
**In Production:**

Starting by collecting some easy stats, shown below along with the Rails console query used to generate.  As if Friday June 10.

Total number of unique projects (i.e. batch_contexts, includes all pre-assembly and discovery report derived jobs): 4432
`BatchContext.count`

Total number of Job Runs (both pre-assembly and discovery report):  9205
`JobRun.count`

Total number of pre-assembly jobs:  4125
`JobRun.where(job_type: 'preassembly').count`

Total number of discovery report jobs: 5080
`JobRun.where(job_type: 'discovery_report').count`

Total number of projects that used a file manifest: 527
` BatchContext.where(using_file_manifest: true).count`

Total number of projects that did not use a file manifest: 3905
` BatchContext.where(using_file_manifest: false).count`

Total number of distinct users who have created projects: 81
`User.count`

Number of projects by user, descending:
` BatchContext.joins(:user).group(:sunet_id).count.sort_by {|_key, value| value}.to_h`
```
{"lmcrae"=>1,
 "krisk11"=>1,
 "presleyh"=>1,
 "bebates"=>1,
 "raymondh"=>1,
 "thalassa"=>1,
 "arcadia"=>2,
 "hfrost"=>2,
 "gdkhalsa"=>3,
 "maj84"=>4,
 "hahn1"=>4,
 "amanheim"=>6,
 "astrids"=>7,
 "amyhodge"=>8,
 "katebar"=>9,
 "itrapido"=>12,
 "ncoy"=>15,
 "dhandel"=>16,
 "caster"=>18,
 "llam813"=>21,
 "ryanlieu"=>24,
 "cebraj"=>24,
 "cheungd"=>25,
 "debauche"=>26,
 "jschne"=>28,
 "jmullike"=>29,
 "mgolson"=>38,
 "dkohrs"=>61,
 "kdurante"=>65,
 "aschweik"=>75,
 "calavt"=>77,
 "lauraw15"=>77,
 "mpetrich"=>137,
 "blalbrit"=>200,
 "bergeraj"=>202,
 "mtrott"=>208,
 "dhartwig"=>253,
 "pchan3"=>534,
 "gwillard"=>2216}
```

**Comment by peetucket** [comment]
Who is using a file_manifest.csv file?

`BatchContext.where(using_file_manifest: true).joins(:user).group(:sunet_id).count.sort_by {|_key, value| value}.to_h`
```
{"calavt"=>1, 
"lmcrae"=>1, 
"debauche"=>1, 
"ryanlieu"=>2, 
"maj84"=>3, 
"dkohrs"=>8, 
"jmullike"=>13, 
"aschweik"=>36, 
"bergeraj"=>50, 
"gwillard"=>412}
```

**Comment by peetucket** [comment]
Number of projects by user, in year increments for the last four years:

`BatchContext.joins(:user).group(:sunet_id).where('batch_contexts.created_at > ? and batch_contexts.created_at < ?',Time.zone.parse('2022/01/01'),Time.zone.parse('2022/12/31')).count.sort_by {|_key, value| value}.to_h`

2022:
```
{"bebates"=>1,
 "blalbrit"=>1,
 "calavt"=>3,
 "debauche"=>3,
 "dhandel"=>3,
 "hahn1"=>3,
 "kdurante"=>3,
 "mpetrich"=>4,
 "itrapido"=>5,
 "jschne"=>7,
 "aschweik"=>11,
 "mtrott"=>12,
 "dkohrs"=>13,
 "bergeraj"=>56,
 "gwillard"=>212}
```

2021:
```
{"lmcrae"=>1,
 "debauche"=>1,
 "llam813"=>1,
 "hahn1"=>1,
 "itrapido"=>2,
 "calavt"=>3,
 "dhandel"=>3,
 "maj84"=>4,
 "jschne"=>4,
 "mpetrich"=>8,
 "ncoy"=>8,
 "katebar"=>9,
 "mgolson"=>11,
 "lauraw15"=>13,
 "cebraj"=>14,
 "kdurante"=>14,
 "ryanlieu"=>17,
 "jmullike"=>18,
 "blalbrit"=>29,
 "mtrott"=>32,
 "dkohrs"=>34,
 "aschweik"=>43,
 "bergeraj"=>58,
 "gwillard"=>405,
 "pchan3"=>534}
```

2020:

```
{"presleyh"=>1,
 "thalassa"=>1,
 "itrapido"=>2,
 "cebraj"=>2,
 "jmullike"=>3,
 "jschne"=>3,
 "gdkhalsa"=>3,
 "ncoy"=>6,
 "dhandel"=>7,
 "dkohrs"=>14,
 "mgolson"=>18,
 "aschweik"=>21,
 "kdurante"=>31,
 "blalbrit"=>35,
 "calavt"=>38,
 "lauraw15"=>40,
 "bergeraj"=>66,
 "mtrott"=>74,
 "mpetrich"=>83,
 "gwillard"=>641}
```

2019:
```
{"ncoy"=>1,
 "krisk11"=>1,
 "raymondh"=>1,
 "hfrost"=>1,
 "itrapido"=>3,
 "amanheim"=>6,
 "cebraj"=>6,
 "ryanlieu"=>7,
 "astrids"=>7,
 "amyhodge"=>7,
 "jmullike"=>8,
 "mgolson"=>8,
 "jschne"=>14,
 "caster"=>14,
 "kdurante"=>17,
 "lauraw15"=>18,
 "debauche"=>19,
 "llam813"=>20,
 "bergeraj"=>22,
 "mpetrich"=>25,
 "cheungd"=>25,
 "calavt"=>33,
 "dhartwig"=>51,
 "mtrott"=>78,
 "blalbrit"=>88,
 "gwillard"=>793}
```
