### ISSUE TITLE
DOC: Update documentation for devel/prepare_content.rb file

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/pre-assembly#95]
This script file is used by the maps accessioning team and has been moved over to sul-dlss/dor-scripts repo.  Once lyberservices-prod goes away, we need to be sure they are still able to run the script from the location where the dor-scripts repo exists.  This will require

1. additional mounts for the /maps servers on dor-services-app VM. 

2. updating the documentation at https://consul.stanford.edu/pages/viewpage.action?pageId=146704638

3. being sure it works for them

**Comment by jmartin-sul** [comment]
though we are still planning to keep the v3-legacy branch of pre-assembly running on lyberservices, this still seems like a worthwhile thing to tackle in this work cycle if possible, because anything that reduces our dependency on lyberservices (getting us closer to being able to shut it down) is a good thing.

**Comment by atz** [comment]
I don't see this as part of this work cycle, so maybe you can give a fuller explanation?

**Comment by peetucket** [comment]
As we continue to run the legacy branch on sul-lyberservices prod, this could be a no-op for now.  Once we get the scripts running in the dor-scripts repo, we would need to do this if we then removed them from the legacy branch.  So could be deferred in my opinion.

**Comment by andrewjbtw** [comment]
Is this still relevant? I know the maps team still does use some features of this script.

**Comment by peetucket** [comment]
Let's close unless it becomes clear the documentation is not good enough.  I haven't had questions about it in a while.
