### ISSUE TITLE
Allow argo style CSV 

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/pre-assembly#952]
In order to allow file level rights in preassembly, we will want to use an Argo style .csv file.

However, for the csv file:
- we probably only care about columns akin to those for file_manifest.csv  ...
- we want file level rights columns to be optional

For now, we may want to accept both types of .csv (the current file_manifest.csv, and the argo one).   

Work with Andrew on a way to distinguish between the two types of manifests, or on the way to cutover to the argo style and discontinue the existing style of file_manifest.csv
- detect it from the column headers?
- a file naming convention to be able to clearly identify when it is an argo style csv (?)

This ticket requires:
- [ ] code to create cocina structural as appropriate for argo style csv, including file level rights (file level rights support could be split into a separate ticket, if warranted)
- [ ] a deployment plan that either accommodates both types of manifests for a while, or that has a timeline for cutover.   Feel free to ask TL to work on this with Andrew.

**Comment by ndushay** [comment]
This is a remider that the cocina structural should default to the ??object level rights?? and NOT default to dark if there are no file level rights.  Also noting in the argo style csv ticket #949.

**Comment by ndushay** [comment]
Double-check with @andrewjbtw that we will need to support both our current file_manifest.csv AND the argo style manifest.csv  for a bit;  if we can switch all in one shot that's easier for us (?)

**Comment by andrewjbtw** [comment]
What about re-titling the headers of the current Preassembly-style to use the Argo-style and supporting that? The preassembly manifest fields all map to the Argo-style columns with one exception: currently the "object" column can be any folder name and does not need to be a druid. We could require it to be a druid.

If that works out then what we would support in Preassembly would be:

- a minimal Argo-style CSV (i.e. - no file-level rights, no mimetypes)
- a full Argo-style CSV (for reaccessioning use cases when you export the Argo-style and then add/modify/delete rows as needed to make the next version via Preassembly)

For users, the change here would be:

- folders have to be named for druids
- change the "object" column in the current CSV to be "druid" and only enter a druid there
- re-title other headers to match the Argo-style

I've had a long-term goal that as long as we need these CSVs they should be as close as possible in structure. The Argo-style structure was based on the Preassembly structure with the addition of the new Cocina-fields (mainly rights, but also file labels), plus a few column header name changes.

**Comment by ndushay** [comment]
@andrewjbtw that would be GREAT!  

However:  do we need a way to distinguish between the minimal CSV and the full style CSV?  By using the header column, perhaps?

**Comment by ndushay** [comment]
@andrewjbtw it would awesome if you could attach an example of the argo-style csv.

**Comment by andrewjbtw** [comment]
You can obtain an Argo-style CSV from any item by going to the show page, navigating to the content section, and clicking on the "download CSV" link, or by using the "Export structural metadata" bulk action.

This is the Argo CSV for https://argo-stage.stanford.edu/view/druid:hc109wn2912
```
druid,resource_label,resource_type,sequence,filename,file_label,publish,shelve,preserve,rights_view,rights_download,rights_location,mimetype,role
hc109wn2912,Video file,video,1,hc109wn2912_Kokaji-Kiri_Dance_Front_Score_pm.mov,hc109wn2912_Kokaji-Kiri_Dance_Front_Score_pm.mov,yes,yes,yes,world,none,,video/quicktime,
hc109wn2912,Video file,video,1,hc109wn2912_Kokaji-Kiri_Dance_Front_Score_thumb.jp2,hc109wn2912_Kokaji-Kiri_Dance_Front_Score_thumb.jp2,yes,yes,yes,world,none,,image/jp2,
hc109wn2912,Video file,video,1,hc109wn2912_Kokaji-Kiri_Dance_Front_Score_sl.mp4,hc109wn2912_Kokaji-Kiri_Dance_Front_Score_sl.mp4,yes,yes,yes,world,none,,video/mp4,
```

This is the file_manifest.csv used in Preassembly to create that object:

```
object,filename,label,sequence,publish,preserve,shelve,resource_type
hc109wn2912,hc109wn2912_Kokaji-Kiri_Dance_Front_Score_pm.mov,Video file,1,no,yes,no,video
hc109wn2912,hc109wn2912_Kokaji-Kiri_Dance_Front_Score_thumb.jp2,Video file,1,yes,yes,yes,video
hc109wn2912,hc109wn2912_Kokaji-Kiri_Dance_Front_Score_sl.mp4,Video file,1,yes,yes,yes,video
```

To translate between an Argo-style CSV and a Preassembly CSV, you would need to rename the columns for the following:

- object (preassembly) = druid (Argo)
- label (preassembly) = resource_label (Argo -- because Cocina also now has file_label and Fedora did not)

All of the other columns would have the same names, only Preassembly uses fewer of them currently. Note that there's one more column supported in Preassembly in addition to the ones in the example above: `role`.

Documentation for the file_manifest.csv is here:
https://github.com/sul-dlss/pre-assembly/wiki/Accessioning-complex-content

**Additional context**

I filed a ticket in Argo to include the druid in all structural CSVs. Currently, no druid is included if you download from a show page (rather than from a bulk action). See https://github.com/sul-dlss/argo/issues/3758

**Comment by andrewjbtw** [comment]
I would consider a minimal preassembly CSV to be the currently supported fields with Argo-style column headers.

**Comment by andrewjbtw** [comment]
Note also that Preassembly currently doesn't use the druid to locate the files in the staging location and instead looks for a folder named for the value in the "object" column. The logic of the `manifest.csv` and `file_manifest.csv` do not require folders to use a druid as a folder name. We might need to change some of that logic if the CSV uses a druid instead.

**Comment by ndushay** [comment]
Is this ticket a duplicate of #879

**Comment by edsu** [comment]
It looks like a duplicate to me. I'm going to leave both open but will leave a note in #1197 to close both tickets on completion.

**Comment by justinlittman** [comment]
closing in favor of #1197
