### ISSUE TITLE
train file_manifest.csv users to use Argo style .csv

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/pre-assembly#953]

**Comment by ndushay** [comment]
is this ticket do-able by anyone other than Andrew?

**Comment by edsu** [comment]
I think @andrewjbtw  would be ideal, since he communicates the most with Preassembly users? But maybe you had something else in mind when you were creating the ticket?

**Comment by andrewjbtw** [comment]
I've updated the documentation and notified the main users of the file manifest. Since all other training is basically on a rolling basis I'm closing this.
