### ISSUE TITLE
reduce memory footprint while discovery reports run

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/pre-assembly#961]
(possibly also true for pre-assembly runs)

likely culprit: `process_digital_objects` - instantiates all and keeps them all in memory

### Options:

1. Perhaps use an enumerator instead of array:  https://github.com/sul-dlss/pre-assembly/blob/main/app/lib/pre_assembly/batch.rb#L74

2.  Make DigitalObject.new https://github.com/sul-dlss/pre-assembly/blob/main/app/lib/pre_assembly/batch.rb#L79 smaller, and/or put it in the loop inside the enumerator that is doing the call.

3.  possibility that the discovery report itself is not performant in how it writes, but it is believed this uses enum and JBuilder and is not in this category.

perhaps work with @jmartin-sul and/or his tooling from #908 to determine how to check if your changes improve things.

**Comment by jmartin-sul** [comment]
this is my incomplete attempt to address this issue and to test my hypothesis from #908:  https://github.com/sul-dlss/pre-assembly/pull/965

**Comment by ndushay** [comment]
PR #965 can be viewed as a possible starting point.  Note: we likely don't want the profiling code or gems for it to get merged to main.
