### ISSUE TITLE
consider reducing memory usage for ObjectValidator.validate if performance is still a concern

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/pre-assembly#970]
Performance analysis for discovery reports indicates that `ObjectValidator.validate` uses a lot of memory.   See issue #908

It's possible this work will be less important after #961 is solved.

See also #864, which essentially says "this method needs a refactor anyway"

Can this method be rewritten to reduce the memory footprint?

Approach suggested:

As with #961, the likely culprits would be:
- all validators are held until all are processed;  using an enum approach (as done as a solution for #961) might be helpful
- we hold the paths for all the object files at once;  is that a problem?  Trickier to improve.

**Comment by ndushay** [comment]
We think PR #965 is sufficent.

**Comment by edsu** [comment]
@ndushay it looks like this issue can be closed given your last comment?
